sensor:
  - platform: template
    sensors: 
      battery_backyard_door_sensor:
        friendly_name: 'Backyard Door Sensor Battery'
        value_template: "{{ states.binary_sensor.door_window_sensor_158d00019e152b.attributes.battery_level|default(-1)|int if states.binary_sensor.door_window_sensor_158d00019e152b is not none }}"
        unit_of_measurement: '%'
        icon_template: '{% if states.binary_sensor.door_window_sensor_158d00019e152b.attributes.battery_level == 100 %}
                           mdi:battery
                        {% elif states.binary_sensor.door_window_sensor_158d00019e152b.attributes.battery_level >= 90 %}
                           mdi:battery-90
                        {% elif states.binary_sensor.door_window_sensor_158d00019e152b.attributes.battery_level >= 80 %}
                           mdi:battery-80
                        {% elif states.binary_sensor.door_window_sensor_158d00019e152b.attributes.battery_level >= 70 %}
                           mdi:battery-70
                        {% elif states.binary_sensor.door_window_sensor_158d00019e152b.attributes.battery_level >= 60 %}
                           mdi:battery-60
                        {% elif states.binary_sensor.door_window_sensor_158d00019e152b.attributes.battery_level >= 50 %}
                           mdi:battery-50
                        {% elif states.binary_sensor.door_window_sensor_158d00019e152b.attributes.battery_level >= 40 %}
                           mdi:battery-40
                        {% elif states.binary_sensor.door_window_sensor_158d00019e152b.attributes.battery_level >= 30 %}
                           mdi:battery-30
                        {% elif states.binary_sensor.door_window_sensor_158d00019e152b.attributes.battery_level >= 20 %}
                           mdi:battery-20
                        {% elif states.binary_sensor.door_window_sensor_158d00019e152b.attributes.battery_level >= 10 %}
                           mdi:battery-10
                        {% else %}
                           battery-outline
                        {% endif %}'
        entity_id: binary_sensor.door_window_sensor_158d00019e152b

automation:
  - alias: Low Battery Sensors
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.battery_backyard_door_sensor
        below: 10
    action:
      - service: notify.ios_isabellas_iphone_6s
        data_template:
          title: 'Battery low'
          message: >
            '{{ trigger.to_state.name }}'