homeassistant:
  # whitelist_external_dirs:
  #   - '/share'
  name: Home
  latitude: !secret lat_coord
  longitude: !secret long_coord
  elevation: 50
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include_dir_merge_named customize
  customize_glob: !include customglob.yaml
  packages: !include_dir_named packages

config:
hassio:
http:
  api_password: !secret http_password
  base_url: !secret base_url
updater:
conversation:
customizer:
  custom_ui: hosted
cloud: !include assistants/cloud.yaml # Alexa
homekit: !include assistants/homekit.yaml
ios: !include notify/ios_config.yaml

# discovery:

# ########################################
# ###                GUI               ###
# ########################################
map:
frontend:
  javascript_version: latest
  themes: !include_dir_named themes
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
    - /local/custom_ui/state-card-value_only.html
    - /local/custom_ui/state-card-tiles.html
panel_iframe:
  ide:
    title: IDE
    icon: mdi:code-braces
    url: !secret ide_address
  terminal:
    title: Terminal
    icon: mdi:console
    url: !secret terminal_address
    
  # mdi_index:
  #   title: MDI Icons
  #   icon: mdi:vector-square
  #   url: !secret mdi_index_url

panel_custom: 
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

# ########################################
# ###              LOGGING             ###
# ########################################

recorder: !include logging/recorder.yaml
history: !include logging/history.yaml
logbook: !include logging/logbook.yaml
logger: !include logging/logger.yaml
sun:

########################################
###               HUBS               ###
########################################
zwave:
  usb_path: /dev/ttyACM0
xiaomi_aqara:
  gateways:
   - mac: !secret xiaomi_mac
     key: !secret xiaomi_key
hue:
  bridges:
    - host: !secret hue_ip
      allow_hue_groups: false

# ########################################
# ###              ENTITES             ###
# ########################################
ring:
  username: !secret ring_username
  password: !secret ring_password
media_player: !include entities/media_player.yaml
scene: !include_dir_merge_list scene
device_tracker: !include entities/device_tracker.yaml
# zone: !include zone.yaml

# ########################################
# ###             SERVICES             ###
# ########################################
notify: !include notify/notify.yaml
python_script:
mqtt:
  discovery: true
  discovery_prefix: homeassistant
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password
mqtt_eventstream:
  # publish_topic: master/topic
  subscribe_topic: slave/rpi
google:
  client_id: !secret google_id
  client_secret: !secret google_secret
ifttt:
  key: !secret ifttt_key
