homeassistant:
  name: Home
  latitude: !secret lat_coord
  longitude: !secret long_coord
  elevation: 50
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include_dir_merge_named customize
  customize_glob: !include customglob.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - '/config/www/motion'
config:
hassio:
http:
  api_password: !secret http_password
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 3
updater:
conversation:
customizer:
cloud: !include assistants/cloud.yaml # Alexa
homekit: !include assistants/homekit.yaml
ios: !include notify/ios_config.yaml

# discovery:

# ########################################
# ###                GUI               ###
# ########################################
map:
frontend:
  javascript_version: latest
  themes: !include_dir_named themes
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
    - /local/custom_ui/state-card-value_only.html
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
    - /local/custom_ui/state-card-tiles_es5.html

panel_iframe:
  ide:
    title: IDE
    icon: mdi:code-braces
    url: !secret ide_address
  terminal:
    title: Terminal
    icon: mdi:console
    url: !secret terminal_address
    
custom_updater:
  # mdi_index:
  #   title: MDI Icons
  #   icon: mdi:vector-square
  #   url: !secret mdi_index_url

# panel_custom: 
#   - name: floorplan
#     sidebar_title: Floorplan
#     sidebar_icon: mdi:home
#     url_path: floorplan
#     config: !include floorplan.yaml


# ########################################
# ###              LOGGING             ###
# ########################################

recorder: !include logging/recorder.yaml
history: !include logging/history.yaml
logbook: !include logging/logbook.yaml
logger: !include logging/logger.yaml
sun:

########################################
###               HUBS               ###
########################################
zwave:
  usb_path: /dev/ttyACM0
deconz:
  host: !secret deconz_ip
  port: !secret deconz_port
  api_key: !secret deconz_api
rfxtrx:
  device: /dev/ttyUSB1
switch:
  platform: rfxtrx
  automatic_add: True
  signal_repetitions: 3
  devices:
    0b11000261bc0cfe05010f70:
      name: Switch 1
    0b11000417bc0cfe09010f70:
      name: Switch 2
    0b11000226bc0cfe09010f70:
      name: Switch 3
    0b11000317bc0cfe08010f70:
      name: Dimmer switch
xiaomi_aqara:
  gateways:
   - mac: !secret xiaomi_mac
     key: !secret xiaomi_key
# hue:
#   bridges:
#     - host: !secret hue_ip
#       allow_hue_groups: false

# ########################################
# ###              ENTITIES             ###
# ########################################
ring:
  username: !secret ring_username
  password: !secret ring_password
verisure:
  username: !secret verisure_username
  password: !secret verisure_password
  alarm: 0
  locks: 1
  
media_player: !include entities/media_player.yaml
scene: !include_dir_merge_list scene
device_tracker: !include entities/device_tracker.yaml
zone: !include zone.yaml

# ########################################
# ###             SERVICES             ###
# ########################################
notify: !include notify/notify.yaml
python_script:
mqtt:
  discovery: true
  discovery_prefix: homeassistant
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password
mqtt_statestream:
  base_topic: hassio
  publish_attributes: true
  publish_timestamps: true
  include:
    entities:
      - counter.litterbox_downstairs_visits
      - counter.litterbox_upstairs_visits
      - input_select.washing_machine_status
# mqtt_eventstream:
#   # publish_topic: master/topic
#   subscribe_topic: slave/rpi
google:
  client_id: !secret google_id
  client_secret: !secret google_secret

ifttt:
  key: !secret ifttt_key
tts:
  - platform: google
shell_command:
  lovelace_gen: 'python /config/lovelace-gen.py'
  lovelace_gen_states: !secret lovelace_gen_states