homeassistant:
  name: Home
  latitude: !secret lat_coord
  longitude: !secret long_coord
  elevation: 50
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include_dir_merge_named customize
  customize_glob: !include customglob.yaml
  packages: !include_dir_named packages
config:
cloud: !include alexa.yaml
        
http:
  api_password: !secret http_password
  base_url: !secret base_url
updater:
# discovery:
conversation:
customizer:
  custom_ui: hosted

# ########################################
# ###                GUI               ###
# ########################################
map:
frontend:
  javascript_version: latest
  themes: !include_dir_named themes
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
    - /local/custom_ui/state-card-value_only.html
    - /local/custom_ui/state-card-tiles.html
  # extra_html_url_es5:
  #   - /local/custom_ui/state-card-tiles.html
# panel_iframe:
#   # grafana:
#   #   title: "Grafana"
#   #   icon: mdi:chart-areaspline
#   #   url: !secret grafana_url
  # mdi_index:
  #   title: MDI Icons
  #   icon: mdi:vector-square
  #   url: !secret mdi_index_url
#   # hadashboard:
#   #   title: HaDashboard
#   #   icon: mdi:television-guide
#   #   url: !secret hadashboard_url
#   # configurator:
#   #   title: Configurator
#   #   icon: mdi:wrench
#   #   url: !secret configurator_url
panel_custom: 
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

# ########################################
# ###              LOGGING             ###
# ########################################

recorder: !include recorder.yaml
history: !include history.yaml
logbook: !include logbook.yaml
logger: !include logger.yaml
sun:

# tts:
#   platform: google
# # influxdb:
# #   host: 127.0.0.1
# #   database: home_assistant
# #   username: !secret influxdb_username
# #   password: !secret influxdb_password


########################################
###               HUBS               ###
########################################
rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A14SREW-if00-port0
  debug:
zwave:
  usb_path: /dev/ttyACM0
  new_entity_ids: true
xiaomi_aqara:
  gateways:
   - mac: !secret xiaomi_mac
     key: !secret xiaomi_key
hue:
  bridges:
    - host: !secret hue_ip
      allow_hue_groups: false

# ########################################
# ###              ENTITES             ###
# ########################################
ring:
  username: !secret ring_username
  password: !secret ring_password
media_player: !include media_player.yaml
scene: !include_dir_merge_list scene
device_tracker: !include device_tracker.yaml
zone: !include zone.yaml

# ########################################
# ###             SERVICES             ###
# ########################################
notify: !include notify.yaml
python_script:
# group: !include_dir_merge_named group/
mqtt:
  broker: !secret mqtt_broker
  port: 1883
  client_id: home-assistant
  username: !secret mqtt_username
  password: !secret mqtt_password
mqtt_statestream:
  base_topic: /homeassistant
  # publish_attributes: true
  # publish_timestamps: true
# google:
#   client_id: !secret google_id
#   client_secret: !secret google_secret
# # ffmpeg:
# #   ffmpeg_bin: /usr/bin/avconv
ifttt:
  key: !secret ifttt_key

########################################
###                IOS               ###
########################################
ios: !include ios_config.yaml

switch:
  - platform: switchbot
    mac: 'EA:E1:11:E2:B1:77'
    name: 'Stefan radiator'