title: Home
views:
  - icon: mdi:information-outline
    id: home
    title: Glances
    cards:
      - type: vertical-stack
        cards:
        - type: glance
          entities:
            - alarm_control_panel.home_alarm
            - sensor.front_door_combined
            - device_tracker.isabella
            - device_tracker.stefan
        - type: glance
          entities:
            - entity: sensor.temperature_stefan
              name: Stefan
            - sensor.temperature_bedroom
            - sensor.temperature_passage
            - entity: sensor.temperature_downstairs_bathroom
              name: Laundry
        - type: glance
          entities:
            - entity: sensor.big_chili_moisture
              name: Big Chili
            - entity: sensor.small_chili_moisture
              name: Small Chili
            - entity: sensor.herbs_moisture
              name: Herbs
        - type: glance
          entities:
            - entity: sensor.big_chili_temperature
              name: Big Chili
            - entity: sensor.small_chili_temperature
              name: Small Chili
            - entity: sensor.herbs_temperature
              name: Herbs
        - type: entity-filter
          entities:
            - entity: sensor.front_door_lock
              name: Lock
            - sensor.front_door
            - sensor.back_door
            - sensor.backyard_door
            - sensor.balcony_door
            - entity: sensor.dining_area_window
              name: Dining area
            - entity: sensor.bedroom_window
              name: Bedroom
            - entity: sensor.front_door_outdoor_movement
              name: Ring motion
            - sensor.hallway_movement
            - sensor.passage_movement
            - sensor.upstairs_hallway_movement
            - sensor.living_room_movement
            - sensor.back_door_camera_movement
            - entity: sensor.yard_storage_door
              name: Storage door
            - sensor.water_heater
            - sensor.kitchen_sink
            - binary_sensor.smoke_sensor_158d0001d37bdd
            - binary_sensor.smoke_sensor_158d0001d37be5
            - binary_sensor.smoke_sensor_158d0001d37c82
          state_filter:
            - 'Open'
            - 'Movement detected'
            - 'Leaking'
            - 'Unlocked'
            - 'Unknown'
          card: 
            type: glance
            # title: Security glance
        - type: entity-filter
          entities:
            - input_text.lights_tiles
            # - group.outdoor_lights_card
            - light.outdoor_lights
            - light.bedroom_ceiling_light
            - light.bedside_lamp
            - light.dining_area_ceiling_light_level  
            - light.kitchen_ceiling_spotlights_level
            - light.floorlamp_reading_light
            - light.christmas_candelabra
            - light.storage_christmas_candelabra
            - light.floorlamp_uplight
            - light.hallway_window_light
            - light.isa_ceiling_light
            - light.living_room_ceiling_light_level
            - light.living_room_spotlights_level
            - light.passage_ceiling_spotlights_level
            - light.stairs_lights_lights
            - light.walk_in_closet_lights
            # - light.stefan_ceiling_light
            - light.stefan_lightstrip
            - light.upstairs_hallway_ceiling_light_level
            - light.gateway_light_34ce008bfc4b
          state_filter:
            - 'on'
          card:
            type: glance

      - type: entities
        entities:
          - sun.sun
          - sensor.front_door_combined
          - sensor.front_door_latest_ding
          - sensor.front_door_latest_motion
          - sensor.mailbox
          - switch.stefan_radiator

#########################################
####             Home view           ####
#########################################

  - icon: mdi:home-heart
    id: info
    title: Home info
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            entities:
              - input_select.air_cleaner
              - sensor.pollen_bjork
              - sensor.pollen_gras
              - sensor.pollen_grabo
          - type: entities
            # title: House Modes
            show_header_toggle: false
            entities:
              - input_boolean.vacation_mode
              - input_boolean.cleaning_day
              - input_boolean.guest_mode
              - input_boolean.isa_mode
          - type: entities
            # title: Laundry
            show_header_toggle: false        
            entities:
              - input_select.washing_machine_status
              - sensor.washer
              # - switch.laundry_line_drying
          - type: entities
            # title: Roomba
            show_header_toggle: false
            entities:
              - input_select.roomba_mode
              - switch.roomba_combined
              - sensor.roomba_docked
              # - switch.roomba
              # - switch.roomba_dock
              # - switch.roomba_dock_living_room
              # - switch.roomba_living_room
              # - sensor.vacuumed_today 

      - type: vertical-stack
        cards:
          - type: history-graph
            title: Temperatures 48h
            hours_to_show: 48
            entities:
              - sensor.temperature_bedroom
              - sensor.temperature_passage
              - sensor.temperature_downstairs_bathroom
              - sensor.temperature_stefan
          - type: history-graph
            title: Temperatures 7 Days
            hours_to_show: 168
            entities:
              - sensor.temperature_bedroom
              - sensor.temperature_passage
              - sensor.temperature_downstairs_bathroom
              - sensor.temperature_stefan

      ## Cameras    
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: picture-entity
                image:
                name: Latest Motion Front Door
                entity: camera.front_door
                camera_image: camera.front_door
              - type: picture-entity
                name: Latest Motion Back Door
                image:
                entity: camera.latest_motion
                camera_image: camera.latest_motion
          - type: horizontal-stack
            cards:
              - type: picture-entity
                image:
                entity: camera.back_door
                name: Live Back Door            
                camera_image: camera.back_door
              - type: picture-entity
                name: Live Upstairs           
                image:
                entity: camera.upstairs
                camera_image: camera.upstairs

#########################################
####           Lights view           ####
#########################################

  - icon: mdi:lightbulb-on
    id: lights
    title: Lights
    cards:
      - type: entities
        entities:
          # - input_text.lights_tiles
          # - group.outdoor_lights_card
          - light.outdoor_lights
          - light.bedroom_ceiling_light
          - light.bedside_lamp
          - light.dining_area_ceiling_light_level  
          - light.kitchen_ceiling_spotlights_level
          - light.floorlamp_reading_light
          - light.christmas_candelabra
          - light.storage_christmas_candelabra
          - light.floorlamp_uplight
          - light.hallway_window_light
          - light.isa_ceiling_light
          - light.living_room_ceiling_light_level
          - light.living_room_spotlights_level
          - light.passage_ceiling_spotlights_level
          - light.stairs_lights_lights
          - light.walk_in_closet_lights
          # - light.stefan_ceiling_light
          - light.stefan_lightstrip
          - light.upstairs_hallway_ceiling_light_level
          - light.gateway_light_34ce008bfc4b