alias: 'Bike Battery Timer'
trigger:
  - platform: state
    entity_id: switch.bike_battery
    to: 'on'
    for:
      minutes: 5
condition:
  condition: numeric_state
  entity_id: sensor.bike_battery_power
  below: '10'
action:
  - service: switch.turn_off
    entity_id: switch.bike_battery