#https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/sensor/devices_states.yaml
- platform: template
  sensors:

      #########################################
      ######         RFX SWITCHES        ######
      #########################################

      motion_sensor:
        friendly_name: 'Nexa motion'
        value_template: '{% if is_state("switch.motion_sensor", "on") %}Occupied{% else %}Not in use{% endif %}'
        icon_template: '{% if is_state("switch.motion_sensor", "on") %}mdi:cat{% else %}mdi:application{% endif %}'


      #########################################
      ######              PIRS           ######
      #########################################


      #########################################
      ######             LIGHTS          ######
      #########################################
 
      # stefan_ceiling_light:
      #   friendly_name: "Stefan Ceiling Light"
      #   value_template: '{% if is_state("light.stefan_ceiling_light", "on") %}on{% else %}off{% endif %}'
      #   icon_template: '{% if is_state("light.stefan_ceiling_light", "on") %}mdi:lightbulb-on{% else %}mdi:lightbulb{% endif %}'