## Turn on outside lights and hallway window light at sunset

- alias: Lights On Outside And Hallway At Sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  action:
    - service: light.turn_on
      entity_id: light.outside_front_light
      data:
        brightness: 127
    - service: light.turn_on
      entity_id: light.outside_yard_light
      data:
        brightness: 127
    - service: light.turn_on
      entity_id: light.hallway_window_light
      data:
        brightness: 45
    - service: light.turn_on
      entity_id: light.outside_yard_hanging_lights

## Turn off outside lights and hallway window light at midnight
- alias: Lights Off Outside And Hallway At Midnight
  trigger:
    platform: time
    at: '23:59:00'
  action:
    - service: homeassistant.turn_off
      entity_id: light.outside_front_light
    - service: homeassistant.turn_off
      entity_id: light.outside_yard_light
    - service: homeassistant.turn_off
      entity_id: light.hallway_window_light
    - service: light.turn_off
      entity_id: light.outside_yard_hanging_lights


## Turn on hallway window light and front outside light if we come home after 00 and turn them off after 10 min
- alias: Lights On Outside And Hallway At Coming Home At Night Delay Ten Then Off
  trigger:
    - platform: zone
      entity_id: device_tracker.stefan_iphone_7
      zone: zone.home
      event: enter
    - platform: zone
      entity_id: device_tracker.isabellas_iphone_6s
      zone: zone.home
      event: enter
  condition:
    condition: time
    after: '00:01:00'
    before: '05:00:00'
  action:
    - service: light.turn_on
      entity_id: light.outside_front_light
      data:
        brightness: 127
    - service: light.turn_on
      entity_id: light.outside_yard_light
      data:
        brightness: 127
    - service: light.turn_on
      entity_id: light.hallway_window_light
      data:
        brightness: 45

    - delay: 0:10
    
    - service: homeassistant.turn_off
      entity_id: light.outside_front_light
    - service: homeassistant.turn_off
      entity_id: light.outside_yard_light
    - service: homeassistant.turn_off
      entity_id: light.hallway_window_light

## Also turn on passage lights, but not turn off
- alias: Lights On Passage At Coming Home At Night
  trigger:
    - platform: zone
      entity_id: device_tracker.stefan_iphone_7
      zone: zone.home
      event: enter
    - platform: zone
      entity_id: device_tracker.isabellas_iphone_6s
      zone: zone.home
      event: enter
  condition:
    condition: time
    after: '00:01:00'
    before: '05:00:00'
  action:
    - service: light.turn_on
      entity_id: light.passage_ceiling_spotlights_level


## Lights on in morning if sun below horizon
- alias: 'Lights On Outside And Hallway At 06:40 If Before Sunrise'
  trigger:
    platform: time
    at: '06:40:00'
  condition:
    condition: sun
    before: sunrise
  action:
    - service: light.turn_on
      entity_id: light.outside_front_light
      data:
        brightness: 127
    - service: light.turn_on
      entity_id: light.outside_yard_light
      data:
        brightness: 127
    - service: light.turn_on
      entity_id: light.hallway_window_light
      data:
        brightness: 45
    - service: light.turn_on
      entity_id: light.outside_yard_hanging_lights

## Lights off at sunrise
- alias: Lights Off Outside And Hallway At Sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: homeassistant.turn_off
      entity_id: light.outside_front_light
    - service: homeassistant.turn_off
      entity_id: light.outside_yard_light
    - service: homeassistant.turn_off
      entity_id: light.hallway_window_light
    - service: light.turn_off
      entity_id: light.outside_yard_hanging_lights