# test with door trigger for presence (if door is not opened I cannot have left) - seems to be working
- alias: 'Stefan away'
  trigger:
    - platform: state
      # entity_id: group.stefan
      entity_id: device_tracker.stefan_iphone_7
      to: 'not_home'
  action:
    # - service: homeassistant.turn_off
    #   entity_id: input_boolean.stefan_home
    - service: notify.ios_isabellas_iphone_6s
      data:
        title: 'Stefan 채r nu rapporterad som inte hemma.'
        message: 'Inte hemma'

- alias: 'Stefan Home'
  trigger:
    - platform: state
      entity_id: device_tracker.stefan_iphone_7
      to: 'home'
  action:
    # - service: homeassistant.turn_on
    #   entity_id: input_boolean.stefan_home
    - service: notify.ios_isabellas_iphone_6s
      data:
        title: 'Stefan 채r nu rapporterad som hemma.'
        message: 'Hemma'


- alias: 'Stefan Bayesian Home'
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: binary_sensor.stefan_home
      to: 'on'
  action:
    - service: notify.ios_isabellas_iphone_6s
      data:
        title: 'Stefan 채r nu rapporterad som hemma.'
        message: 'via bayesian'

- alias: 'Stefan Bayesian Not Home'
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: binary_sensor.stefan_home
      to: 'off'
  action:
    - service: notify.ios_isabellas_iphone_6s
      data:
        title: 'Stefan 채r nu rapporterad som inte hemma.'
        message: 'via bayesian'



- alias: Presence Force Check Location
  trigger:
    - platform: state
      entity_id: sensor.front_door
      to: 'Open'
    - platform: state
      entity_id: sensor.back_door
      to: 'Open'
    - platform: homeassistant
      event: start
  action:
  # Catch home
  - service: notify.ios_stefan_iphone_7
    data:
      message: "request_location_update"
  - service: notify.ios_isabellas_iphone_6s
    data:
      message: "request_location_update"
  - delay: '00:10:00'
  # catch not_home
  - service: notify.ios_stefan_iphone_7
    data:
      message: "request_location_update"
  - service: notify.ios_isabellas_iphone_6s
    data:
      message: "request_location_update"