homeassistant:
  customize:
    switch.air_cleaner_quiet_auto:
      homebridge_visible: true
        
switch:
  - platform: broadlink
    friendly_name: Broadlink Bedroom
    host: !secret broadlink_bedroom_ip
    mac: !secret broadlink_bedroom_mac
    switches:
      air_cleaner_quiet_auto:
        friendly_name: Air Cleaner Quiet
        command_on: 'JgBQAAABI5MRFBE4FBETEhQ1EhMTEhMSFDUSExQ2EjgSExQ2EjgSOBE5ERQTEhQQFBEUERQQFRAUERQ1EjgSOBI4EjgTNxM2FAAFJQABAUoUAA0FAAAAAAAAAAA='
        command_off: 'JgBQAAABJJUTEhM2FBEUERQ2FBEUERQRFDYUERQ2FDYUERQ1FDYUNhQ2FBEUERQRFDYTEhMSExITERQ2FDYUNhQRFDUUNhQ2FAAFJAABJ0oSAA0FAAAAAAAAAAA='


automation:
  - alias: Air Cleaner To Quiet at 21
    initial_state: 'on'
    trigger:
      - platform: time
        at: '21:00:00'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.air_cleaner_quiet
      # - service: notify.ios_isabellas_iphone_6s
      #   data:
      #     message: 'Set to quiet'
      #     title: 'Air cleaner'

  - alias: Air Cleaner To Auto At 11
    initial_state: 'on'
    trigger:
      - platform: time
        at: '11:00:00'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.air_cleaner_quiet
      # - service: notify.ios_isabellas_iphone_6s
      #   data:
      #     message: 'Set to auto'
      #     title: 'Air cleaner'