homeassistant:
  customize:
    input_text.air_tiles:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 3
        column_width: 50px
        row_height: 50px
        gap: 15px
        color: '#555B65'
        color_on: '#D5D619'
        color_off: '#BBBEC2'
        entities:
          - entity: script.air_cleaner_quiet
            # label: S1
            row: 1
            column: 1
            icon: mdi:fan-off
          - entity: script.air_cleaner_auto
            # label: S1
            row: 1
            column: 2
            icon: mdi:fan
          - entity: script.air_cleaner_turbo
            # label: S1
            row: 1
            column: 3
            icon: mdi:run-fast

switch:
  - platform: broadlink
    friendly_name: Broadlink Bedroom
    host: !secret broadlink_bedroom_ip
    mac: !secret broadlink_bedroom_mac

input_text:
  air_tiles:
    name: Tiles

script:
  air_cleaner_quiet:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_53
        data:
          packet:
            - 'JgBQAAABI5MRFBE4FBETEhQ1EhMTEhMSFDUSExQ2EjgSExQ2EjgSOBE5ERQTEhQQFBEUERQQFRAUERQ1EjgSOBI4EjgTNxM2FAAFJQABAUoUAA0FAAAAAAAAAAA='
  air_cleaner_auto:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_53
        data:
          packet:
            - 'JgBQAAABJJUTEhM2FBEUERQ2FBEUERQRFDYUERQ2FDYUERQ1FDYUNhQ2FBEUERQRFDYTEhMSExITERQ2FDYUNhQRFDUUNhQ2FAAFJAABJ0oSAA0FAAAAAAAAAAA='
  air_cleaner_turbo:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_53
        data:
          packet:
            - 'JgBYAAABIJITEhI4EhMSExI4EhMSExITEjgSExI4EjgRFBE4EjgSOBITEjgSOBITEjgRFBEUERQROBIUERQROBITEjgSOBI4EgAFJwABIEkSAAxXAAEdShMADQU='
  # air_cleaner_toggle:
  #   sequence:
  #     - service: switch.broadlink_send_packet_192_168_1_53
  #       data:
  #         packet:
  #           - 'JgBQAAABKpIUERQ2FBEUERQ2ExITEhMSEzYUERQ2FDYUERQ2FDUUNhQ2FDYUERQ2ExITEhMSExITERQRFDYUERQ2FDYUNhM2FAAFJQABKUkUAA0FAAAAAAAAAAA='
            

input_select:
  air_cleaner:
    name: Air cleaner
    options:
     - Quiet
     - Auto
     - Turbo
    initial: Quiet
    icon: mdi:air-conditioner

automation:
  - alias: Air Cleaner Quiet
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.air_cleaner
        to: 'Quiet'
    action:
      - service: script.turn_on
        entity_id: script.air_cleaner_quiet

  - alias: Air Cleaner Auto
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.air_cleaner
        to: 'Auto'
    action:
      - service: script.turn_on
        entity_id: script.air_cleaner_auto

  - alias: Air Cleaner Turbo
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.air_cleaner
        to: 'Turbo'
    action:
      - service: script.turn_on
        entity_id: script.air_cleaner_turbo

  - alias: Air Cleaner To Turbo On High Pollen
    initial_state: 'on'
    trigger:
      - platform: time
        at: '20:00:00'
    condition:
      - condition: state
        entity_id: sensor.pollen_levels
        state: 'high'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.air_cleaner
          option: 'Turbo'

  - alias: Air Cleaner To Quiet at 21
    initial_state: 'on'
    trigger:
      - platform: time
        at: '21:00:00'
    action:
      # - service: input_select.select_option
      #   data:
      #     entity_id: input_select.air_cleaner
      #     option: 'Quiet'
      - service: script.turn_on
        entity_id: script.air_cleaner_quiet

  - alias: Air Cleaner To Auto At 11
    initial_state: 'on'
    trigger:
      - platform: time
        at: '11:00:00'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.air_cleaner
          option: 'Auto'