homeassistant:
  customize:
    alarm_control_panel.home_alarm:
      homebridge_visible: true
      homebridge_name: House Alarm

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    # code:
    pending_time: 0
    disarm_after_trigger: 'false'
    armed_away:
      pending_time: 0
    triggered:
      pending_time: 0   

group:
  security_card:
    view: no
    name: Security
    icon: mdi:home-variant
    entities:
      - alarm_control_panel.home_alarm
      - sensor.last_seen_motion
      - sensor.front_door
      - sensor.back_door
      - sensor.backyard_door
      - sensor.balcony_door
      - sensor.dining_area_window
      - sensor.front_door_outside_movement
      - sensor.hallway_movement
      - sensor.passage_movement
      - sensor.upstairs_hallway_movement
      - sensor.living_room_movement
      - sensor.back_door_camera_movement
      - sensor.yard_storage_door
      - sensor.water_heater
      - sensor.kitchen_sink
      - binary_sensor.smoke_sensor_158d0001d37bdd
      - binary_sensor.smoke_sensor_158d0001d37be5
      - binary_sensor.smoke_sensor_158d0001d37c82

automation:
- alias: 'Alarm Arm Away'
  initial_state: 'on'
  trigger:
      - platform: state
        entity_id: group.persons
        to: 'not_home'
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.home_alarm
    - service: notify.pushbullet_isa
      data_template:
        title: 'Alarm Armed Away'
        message: >
          '{{ trigger.to_state.last_changed }}'

- alias: 'Alarm Arm Home'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.persons
      to: 'home'
  condition:
    condition: template
    value_template: '{{ states.alarm_control_panel.home_alarm.state != armed_home}}'
  action:
    - service: alarm_control_panel.alarm_arm_home
      entity_id: alarm_control_panel.home_alarm
    - service: notify.pushbullet_isa
      data_template:
        title: 'Alarm Armed Home'
        message: >
          '{{ trigger.to_state.last_changed }}'

- alias: 'Alarm Arm Night'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.day_mode
      to: 'Night'
    - platform: time
      at: '00:00:00'
  action:
    - service: alarm_control_panel.alarm_arm_night
      entity_id: alarm_control_panel.home_alarm

- alias: 'Alarm Disarm'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.persons
      to: 'home'
    - platform: time
      at: '06:40:00'
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.home_alarm


- alias: 'Alarm Trigger While Armed Away'
  initial_state: 'on'
  trigger:
      # the other pirs are triggered by the cats
      - platform: state
        entity_id: binary_sensor.passage_pir_sensor
        to: 'on'
      - platform: state
        entity_id: binary_sensor.upstairs_hallway_pir_sensor
        to: 'on'
      - platform: state
        entity_id: sensor.front_door_access_control
        to: '22'
      - platform: state
        entity_id: binary_sensor.back_door_sensor
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001a3e45e ## Balcony
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00019e152b ## Backyard
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00019f5110 ## Yard Storage
        to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_alarm
    - service: notify.ios_isabellas_iphone_6s
      data_template:
        title: 'Alarm triggered'
        message: >
          '{{ trigger.to_state.name }}'

- alias: 'Alarm Trigger While Armed Away Camera Motion'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.back_door_camera_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
  action:
    - service: notify.ios_isabellas_iphone_6s
      data:
        message: Fire Camera Motion
        data:
          attachment:
            content-type: jpeg
          push:
            category: camera
          entity_id: camera.back_door

- alias: 'Alarm Trigger While Armed Home Or Night'
  initial_state: 'on'
  trigger:
      - platform: state
        entity_id: sensor.front_door_access_control
        to: '22'
      - platform: state
        entity_id: binary_sensor.back_door_sensor
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001a3e45e ## Balcony
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00019e152b ## Backyard
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00019f5110 ## Yard Storage
        to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_home
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_night    
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_alarm
    - service: notify.ios_isabellas_iphone_6s
      data_template:
        title: 'Alarm triggered'
        message: >
          '{{ trigger.to_state.name }}'