homeassistant:
  customize:
    alarm_control_panel.home_alarm:
      homebridge_visible: true    
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    # code:
    armed_home:
      pending_time: 0


automation:
- alias: 'Alarm Arm away'
  initial_state: 'on'
  trigger:
      - platform: state
        entity_id: group.persons
        to: 'not_home'
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.home_alarm
    - service: notify.ios_isabellas_iphone_6s
      data_template:
        title: 'Alarm Armed Away'
        message: >
          '{{ trigger.to_state.last_changed }}'

- alias: 'Alarm Arm home'
  initial_state: 'on'
  trigger:
      - platform: state
        entity_id: device_tracker.stefan_iphone_7
        to: 'not_home'
  condition:
    - condition: state
      entity_id: device_tracker.isabellas_iphone_6s
      state: 'home'
  action:
    - service: alarm_control_panel.alarm_arm_home
      entity_id: alarm_control_panel.home_alarm
    - service: notify.ios_isabellas_iphone_6s
      data_template:
        title: 'Alarm Armed Home'
        message: >
          '{{ trigger.to_state.last_changed }}'

- alias: 'Alarm Arm night'
  initial_state: 'on'
  trigger:
    platform: time
    at: '00:01:00'
  action:
    - service: alarm_control_panel.alarm_arm_night
      entity_id: alarm_control_panel.home_alarm

- alias: 'Alarm Disarm'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.persons
      to: 'home'
    - platform: time
      at: '06:00:00'
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.home_alarm
    - service: notify.ios_isabellas_iphone_6s
      data_template:
        title: 'Alarm Disarmed'
        message: >
          '{{ trigger.to_state.last_changed }}'

- alias: 'Alarm Trigger while armed away'
  initial_state: 'on'
  trigger:
  ## Add pirs when fixed the cat false trigger
    # - platform: state
    #   entity_id: sensor.pir1
    #   to: 'active'
    # - platform: state
    #   entity_id: sensor.pir2
    #   to: 'active'
      - platform: state
        entity_id: sensor.front_door_access_control
        to: '22'
      - platform: state
        entity_id: binary_sensor.back_door_sensor
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001a3e45e ## Balcony
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00019e152b ## Backyard
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00019f5110 ## Yard Storage
        to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_alarm
    - service: notify.ios_isabellas_iphone_6s
      data_template:
        title: 'Alarm triggered'
        message: >
          '{{ trigger.to_state.name }}'

- alias: 'Alarm Trigger while armed home or night'
  initial_state: 'on'
  trigger:
      - platform: state
        entity_id: sensor.front_door_access_control
        to: '22'
      - platform: state
        entity_id: binary_sensor.back_door_sensor
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001a3e45e ## Balcony
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00019e152b ## Backyard
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00019f5110 ## Yard Storage
        to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_home
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_night    
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_alarm
    - service: notify.ios_isabellas_iphone_6s
      data_template:
        title: 'Alarm triggered'
        message: >
          '{{ trigger.to_state.name }}'