homeassistant:
  customize:
    sensor.isabellas_iphone_x_battery_state:
      icon: mdi:battery-charging
    sensor.isabellas_iphone_x_battery_level:
      icon: mdi:battery
    sensor.paddan_battery_level:
      icon: mdi:battery
    sensor.paddan_battery_state:
      icon: mdi:battery-charging
    sensor.sensative_door_battery:
      icon: mdi:battery

group:
  battery_status_view:
    icon: mdi:battery-unknown
    view: yes
    entities:
      - group.ebike_battery
      - group.device_batteries
      - group.battery_alert

  device_batteries:
    name: Device Batteries
    entities:
      - sensor.ring_front_door_battery
      - sensor.igrims_battery_level
      - sensor.igrims_battery_state
      - sensor.isabellas_iphone_x_battery_level
      - sensor.isabellas_iphone_x_battery_state
      - sensor.paddan_battery_level
      - sensor.paddan_battery_state

  # ebike group in ebike package

automation:
  - alias: Low Battery Ipad
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.paddan_battery_level
        below: 20
    condition:
      condition: state
      entity_id: sensor.paddan_battery_state
      state: 'Unplugged'
    action:
      - service: notify.ios_isabellas_iphone_x
        data_template:
          title: 'Battery low'
          message: '{{ trigger.to_state.name }}'