homeassistant:
  customize:
    script.dafang_up:
      icon: mdi:chevron-up
    script.dafang_down:
      icon: mdi:chevron-down
    script.dafang_left:
      icon: mdi:chevron-left
    script.dafang_right:
      icon: mdi:chevron-right
    switch.dafang_h264_rtsp_server:
      icon: mdi:power-standby
      name: Dafang switch

camera:
  - platform: ffmpeg
    name: DaFang
    input: -rtsp_transport tcp -i rtsp://192.168.1.79:8554/unicast

script:
  dafang_up:
    sequence:
      - service: cover.open_cover
        data:
          entity_id: cover.dafang_move_updown
  dafang_down:
    sequence:
      - service: cover.close_cover
        data:
          entity_id: cover.dafang_move_updown
  dafang_left:
    sequence:
      - service: cover.open_cover
        data:
          entity_id: cover.dafang_move_leftright
  dafang_right:
    sequence:
      - service: cover.close_cover
        data:
          entity_id: cover.dafang_move_leftright