camera:
  - platform: ffmpeg
    name: Back Door
    input: !secret camera_input
    extra_arguments: -pred 1
  - platform: local_file
    file_path: /config/www/motion/back_door_camera_latest.jpg
    name: Latest motion
binary_sensor:
  - platform: ffmpeg_motion
    name: Back Door Camera Motion
    input: !secret camera_input
    changes: 4
    reset: 30

sensor:  
  - platform: template
    sensors:
      back_door_camera_movement:
        friendly_name: 'Back Door Camera Movement'
        value_template: '{% if is_state("binary_sensor.back_door_camera_motion", "on") %}Movement detected{% else %}No movement{% endif %}'
        icon_template: '{% if is_state("binary_sensor.back_door_camera_motion", "on") %}mdi:run-fast{% else %}mdi:sleep{% endif %}'


# automation:
#   - alias: 'Camera Fireplace Notification On High Temperature'
#     initial_state: 'on'
#     trigger:
#       - platform: numeric_state
#         entity_id: sensor.temperature_passage
#         above: 27
#     action:
#       - service: notify.ios_isabellas_iphone_x
#         data:
#           message: Fire Camera Motion
#           data:
#             attachment:
#               content-type: jpeg
#             push:
#               category: camera
#             entity_id: camera.back_door_cam
  # - alias: 'Camera Motion Snapshot'
  #   initial_state: 'on'
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.back_door_camera_motion
  #       to: 'on'
  #   action:
  #     service: camera.snapshot
  #     data_template:
  #       entity_id: camera.back_door_cam
  #       filename: '/config/www/motion/back_door_camera.jpg'