homeassistant:
  customize:
    input_boolean.cleaning_day:
      confirm_controls_show_lock: true

input_boolean:
  cleaning_day:
    name: Cleaning Day
    initial: off
    icon: mdi:broom


automation:
  - alias: Cleaning Day Automations Off
    trigger:
      - platform: state
        entity_id: input_boolean.cleaning_day
        to: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: automation.light_hallway_brighter_on_motion

  - alias: Cleaning Day Over Automations On
    trigger:
      - platform: state
        entity_id: input_boolean.cleaning_day
        to: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: automation.light_hallway_brighter_on_motion