homeassistant:
  customize_glob:
    group.info_badge_group:
      state_card_mode: badges

group:
  default_view:
    view: yes
    name: Info
    icon: mdi:information-outline
    entities:
      - device_tracker.isabella
      - device_tracker.stefan
      - group.summary
      - group.info_card
      # - input_boolean.stefan_home
      # - input_boolean.isabella_home
      - input_select.isa_status_dropdown
      - input_select.stefan_status_dropdown
      - group.lights
      - group.door_alerts
      - group.security_card


  info_card:
    name: Info
    control: hidden
    entities:
      - group.inside_temperatures
      - group.plant_moisture
      - sun.sun
      - alarm_control_panel.home_alarm
      # - sensor.front_door_lock
      - sensor.front_door_combined      
      - sensor.last_seen_motion
      - sensor.last_door_opened
      - sensor.front_door_latest_ding
      - sensor.front_door_latest_motion
      - sensor.mailbox
      # - input_boolean.car_heater
      - switch.stefan_radiator
      # - input_boolean.test
  info_badge_group:
    name: Badge group
    entities:
      - sensor.temperature_158d0001235510
      - sensor.temperature_158d000123552c
      - sensor.temperature_158d0001a2a899
      - sensor.temperature_158d0001fd83e7
      - sensor.small_chili_moisture
      - sensor.big_chili_moisture

  everything_view:
    view: yes
    name: All
    entities:
      - group.all_automations
      - group.all_devices
      - group.all_lights
      - group.all_switches
      - group.all_zwave
      - group.all_scripts
      - group.all_plants
      - device_tracker.isabella
      - device_tracker.stefan