homeassistant:
  customize:
    binary_sensor.white6:
      friendly_name: Doorbell
      # homebridge_visible: true

switch:
  - platform: rfxtrx
    signal_repetitions: 3
    devices:
      0b11000f0190965201040f70:
        name: Doorbell Front Door
        fire_event: true

input_boolean:
  doorbell_ringing:
    name: Doorbell is ringing
    initial: off

automation:
  - alias: Doorbell Front Door Trigger Boolean
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: button_pressed
        event_data: 
          state: 'group on'
          entity_id: switch.doorbell_front_door
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.doorbell_ringing    

  - alias: Doorbell Front Door Ring
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.doorbell_ringing
        to: 'on'
    action:
      # - service_template: >
      #     {% if (is_state('device_tracker.isabella', 'home')) and (is_state('device_tracker.stefan', 'home'))  %}
      #       notify.all
      #     {% elif is_state('device_tracker.isabella', 'home') %}
      #       notify.ios_isabellas_iphone_6s
      #     {% elif is_state('device_tracker.stefan', 'home') %}
      #       notify.ios_stefan_iphone_7
      #     {% endif %}
      #   data:
      #     title: 'Doorbell ringing!'
      #     message: 'Someone is at the front door'
      - service: notify.pushbullet_isa
        data:
          title: 'Doorbell ringing!'
          message: 'Someone is at the front door'
      - service: notify.pushbullet_stefan
        data:
          title: 'Doorbell ringing!'
          message: 'Someone is at the front door'
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret xiaomi_mac
          ringtone_id: 10
          ringtone_vol: 10
      - service: python_script.flash_lights_upstairs_hallway_and_yard
      - service: homeassistant.turn_off
        entity_id: input_boolean.doorbell_ringing