homeassistant:
  customize:
    binary_sensor.door_window_sensor_158d00019f5110:
      friendly_name: Yard Storage Door
      homebridge_visible: true
      homebridge_name: Yard Storage Door
      device_class: opening

    binary_sensor.door_window_sensor_158d00019e152b:
      friendly_name: Backyard Door
      homebridge_visible: true
      homebridge_name: Backyard Door
      device_class: opening

    binary_sensor.door_window_sensor_158d0001a3e45e:
      friendly_name: Balcony Door
      homebridge_visible: true
      homebridge_name: Balcony Door
      device_class: opening

    binary_sensor.front_door_homebridge:
      homebridge_visible: true
      homebridge_name: Front Door
      friendly_name: Front Door
      device_class: opening

    binary_sensor.back_door_sensor:
      friendly_name: Back Door
      homebridge_visible: true
      homebridge_name: Back Door
      device_class: opening

    sensor.front_door_access_control:
      homebridge_name: Front Door

      
  customize_glob:
    sensor.*door*:
      custom_ui_state_card: state-card-custom-ui
      templates:
        hs_color: "if (state === 'Closed') return [0, 0];
        else if (state === 'Unknown') return [40, 70];
        else if (state === 'Open') return [0, 85];"

    sensor.*window*:
      custom_ui_state_card: state-card-custom-ui
      templates:
        hs_color: "if (state === 'Closed') return [0, 0];
        else if (state === 'Unknown') return [40, 70];
        else if (state === 'Open') return [0, 85];"

    sensor.*lock*:
      custom_ui_state_card: state-card-custom-ui
      templates:
        hs_color: "if (state === 'Locked') return [0, 0];
        else if (state === 'Unknown') return [40, 70];
        else if (state === 'Unlocked') return [0, 85];"
    sensor.front_door_combined:
      custom_ui_state_card: state-card-custom-ui
      templates:
        hs_color: "if (state === 'Locked and Closed') return [0, 0];
        else if (state === 'Locked and Open') return [0, 85];
        else if (state === 'Unlocked and Open') return [0, 85];
        else return [40, 70];"

sensor:
  - platform: template
    sensors:
      front_door:
        friendly_name: 'Front Door'
        value_template: '{% if is_state("sensor.front_door_access_control", "22") %}Open{% elif is_state("sensor.front_door_access_control", "23")%}Closed{% else %}Unknown{% endif %}'
        icon_template: '{% if is_state("sensor.front_door_access_control", "22") %}mdi:door-open{% elif is_state("sensor.front_door_access_control", "23")%}mdi:door{% else %}mdi:comment-question-outline{% endif %}'

      backyard_door:
        friendly_name: 'Back Yard Door'
        value_template: '{% if is_state("binary_sensor.door_window_sensor_158d00019e152b", "on") %}Open{% elif is_state("binary_sensor.door_window_sensor_158d00019e152b", "off")%}Closed{% else %}Unknown{% endif %}'
        icon_template: '{% if is_state("binary_sensor.door_window_sensor_158d00019e152b", "on") %}mdi:door-open{% elif is_state("binary_sensor.door_window_sensor_158d00019e152b", "off")%}mdi:door{% else %}mdi:comment-question-outline{% endif %}'

      back_door:
        friendly_name: 'Back Door'
        value_template: '{% if is_state("binary_sensor.back_door_sensor", "on") %}Open{% elif is_state("binary_sensor.back_door_sensor", "off")%}Closed{% else %}Unknown{% endif %}'
        icon_template: '{% if is_state("binary_sensor.back_door_sensor", "on") %}mdi:door-open{% elif is_state("binary_sensor.back_door_sensor", "off")%}mdi:door{% else %}mdi:comment-question-outline{% endif %}'
      
      balcony_door:
        friendly_name: 'Balcony Door'
        value_template: '{% if is_state("binary_sensor.door_window_sensor_158d0001a3e45e", "on") %}Open{% elif is_state("binary_sensor.door_window_sensor_158d0001a3e45e", "off")%}Closed{% else %}Unknown{% endif %}'
        icon_template: '{% if is_state("binary_sensor.door_window_sensor_158d0001a3e45e", "on") %}mdi:door-open{% elif is_state("binary_sensor.door_window_sensor_158d0001a3e45e", "off")%}mdi:door{% else %}mdi:comment-question-outline{% endif %}'
              
      yard_storage_door:
        friendly_name: 'Yard Storage Door'
        value_template: '{% if is_state("binary_sensor.door_window_sensor_158d00019f5110", "on") %}Open{% elif is_state("binary_sensor.door_window_sensor_158d00019f5110", "off")%}Closed{% else %}Unknown{% endif %}'
        icon_template: '{% if is_state("binary_sensor.door_window_sensor_158d00019f5110", "on") %}mdi:door-open{% elif is_state("binary_sensor.door_window_sensor_158d00019f5110", "off")%}mdi:door{% else %}mdi:comment-question-outline{% endif %}'

binary_sensor:
  - platform: template
    sensors:
      front_door_homebridge:
        friendly_name: "Front Door"
        value_template: '{% if is_state("sensor.front_door_access_control", "22") %}on{% else %}off{% endif %}'

alert:
  backyard_door_open:
    name: Backyard Door left open
    done_message: Door closed
    entity_id: binary_sensor.door_window_sensor_158d00019e152b
    state: 'on'
    repeat: 2
    skip_first: True
    notifiers:
      - ios_isabellas_iphone_x
  front_door_open:
    name: Front Door left open
    done_message: Door closed
    entity_id: sensor.front_door_access_control
    state: '22'
    repeat: 2
    skip_first: True
    notifiers:
      - ios_isabellas_iphone_x
  back_door_open:
    name: Back Door left open
    done_message: Door closed
    entity_id: binary_sensor.back_door_sensor
    state: 'on'
    repeat: 10
    skip_first: True
    notifiers:
      - ios_isabellas_iphone_x
  balcony_door_open:
    name: Balcony Door left open
    done_message: Door closed
    entity_id: binary_sensor.door_window_sensor_158d0001a3e45e
    state: 'on'
    repeat: 1
    skip_first: True
    notifiers:
      - ios_isabellas_iphone_x
  yard_storage_door_open:
    name: Yard Storage Door left open
    done_message: Door closed
    entity_id: binary_sensor.door_window_sensor_158d00019f5110
    state: 'on'
    repeat:
      - 60
      - 30
      - 15
      - 5
    skip_first: True
    notifiers:
      - ios_isabellas_iphone_x

group:
  door_alerts:
    name: Alerts
    entities:
      - alert.back_door_open
      - alert.backyard_door_open
      - alert.front_door_open
      - alert.balcony_door_open
      - alert.yard_storage_door_open

  doors_and_windows:
    view: no
    name: Security
    icon: mdi:home-variant
    entities:   
      - sensor.front_door
      - sensor.back_door
      - sensor.backyard_door
      - sensor.balcony_door
      - sensor.dining_area_window
      - sensor.bedroom_window
      - sensor.yard_storage_door
      
automation:
  - alias: Light Outdoor On When Door Opens
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00019e152b, binary_sensor.back_door_sensor
        to: 'on'
      - platform: state
        entity_id: sensor.front_door_access_control
        to: '22'
    condition:
      - condition: sun
        after: sunset
        after_offset: "-00:45:00"
    action:
      - service: python_script.brighten_then_restore
        data_template:
          entity_id: 'light.outdoor_front_light'
      - service: python_script.brighten_then_restore
        data_template:
          entity_id: 'light.outdoor_yard_light'
      - service: python_script.brighten_then_restore
        data_template:
          entity_id: 'light.outdoor_yard_hanging_lights'