homeassistant:
  customize:
    sensor.water_heater:
      hidden: false

sensor:
  - platform: template  
    sensors:
      water_heater:
        friendly_name: 'Water Heater'
        value_template: '{% if is_state("binary_sensor.water_heater_sensor", "on") %}Leaking{% else %}No leak{% endif %}'
        icon_template: '{% if is_state("binary_sensor.water_heater_sensor", "on") %}mdi:water{% else %}mdi:water-off{% endif %}'
