homeassistant:
  customize:
    sensor.water_heater:
      hidden: false
      homebridge_visible: true

sensor:
  - platform: template  
    sensors:
      water_heater:
        friendly_name: 'Water Heater'
        value_template: '{% if is_state("binary_sensor.water_heater_sensor", "on") %}Leaking{% else %}No leak{% endif %}'
        icon_template: '{% if is_state("binary_sensor.water_heater_sensor", "on") %}mdi:water{% else %}mdi:water-off{% endif %}'

alert:
  water_heater_flooding:
    name: The water heater is leaking!
    entity_id: binary_sensor.water_heater_sensor
    state: 'on'
    repeat: 60
    skip_first: False
    notifiers:
      - ios_isabellas_iphone_6s