# homeassistant:
input_boolean:
  goodnight_stefan:
    name: Goodnight Stefan
    initial: off
  goodnight_isa:
    name: Goodnight Isa
    initial: off
script:
  goodnight:
    alias: Goodnight
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id: group.inside_lights_automations
          transition: 30
      - wait_template: "{{ states.light.bedside_lamp.state == 'off' }}"
      - service: light.turn_on
        data:
          entity_id: light.bedside_lamp
          brightness: 25
      - delay: 
          seconds: 10
      - service: light.turn_on
        data:
          entity_id: light.gateway_light_34ce008bfc4b
          brightness: 255
          rgb_color:
            - 253
            - 64
            - 6
      - delay:
          minutes: 3
      - service: light.turn_off
        data:
          entity_id: light.gateway_light_34ce008bfc4b

automation:
  - alias: Goodnight Isa
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.isabellas_iphone_6s_battery_state
        to: 'Charging'
    condition:
      condition: and
      conditions:
        - condition: time
          before: '06:00:00'        
          after: '21:00:00'
        - condition: state
          entity_id: device_tracker.isabella
          state: 'Home'
        - condition: state
          entity_id: sensor.isa_computer
          state: 'Offline'
        - condition: state
          entity_id: sensor.isa_laptop
          state: 'Offline'
    action:
      - service: notify.ios_isabellas_iphone_6s
        data:
          title: 'Phone charging'
          message: 'Goodnight Isa!'

  - alias: Goodmorning Isa
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.isabellas_iphone_6s_battery_state
        to: 'Unplugged'
    condition:
      condition: and
      conditions:
        - condition: time
          after: '03:30:00'
          before: '12:00:00'
        - condition: state
          entity_id: device_tracker.isabella
          state: 'Home'
    action:
      - service: notify.ios_isabellas_iphone_6s
        data:
          title: 'Phone unplugged'
          message: 'Goodmorning Isa!'

  - alias: Goodnight Stefan
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.igrims_battery_state
        to: 'Charging'
    condition:
      condition: and
      conditions:
        - condition: time
          after: '21:00:00'
          before: '06:00:00'
    action:
      - service: notify.ios_isabellas_iphone_6s
        data:
          title: 'Phone charging'
          message: 'Goodnight Stefan!'

  - alias: Goodmorning Stefan
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.igrims_battery_state
        to: 'Unplugged'
    condition:
      condition: and
      conditions:
        - condition: time
          after: '03:30:00'
          before: '12:00:00'
        - condition: state
          entity_id: device_tracker.stefan
          state: 'Home'
    action:
      - service: notify.ios_isabellas_iphone_6s
        data:
          title: 'Phone unplugged'
          message: 'Goodmorning Stefan!'