homeassistant:
  customize:
    input_boolean.isa_asleep:
      icon: mdi:sleep
#-------------------------------------------

## ADD Bayesian sensor for sleep


input_boolean:
  isa_asleep:
    name: Isa is asleep

#-------------------------------------------

automation:
  - alias: Goodnight Isa
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.white4
        to: 'on'
    condition:
      condition: state
      entity_id: input_boolean.isa_asleep
      state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.isa_asleep
      - service: light.turn_off
        entity_id: light.isa_ceiling_light
      - service: notify.ios_isabellas_iphone_6s
        data:
          title: 'Goodnight!'
          message: 'Dont forget the pill, your lenses or the litter boxes!'

  - alias: Goodmorning Isa
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.white4
        to: 'on'
    condition:
      condition: state
      entity_id: input_boolean.isa_asleep
      state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.isa_asleep
      - service: notify.ios_isabellas_iphone_6s
        data:
          title: 'Good morning!'
          message: 'Dont forget the pill, your lenses or the litter boxes!'