homeassistant:
  customize:
    input_text.dummy_tiles_main:
          custom_ui_state_card: state-card-tiles
          config:
            columns: 6           
            row_height: 54px      
            gap: 8px              
            color: 'hsl(192, 96%, 48%)'                  
            entities:
              - entity: device_tracker.stefan
                label_state: device_tracker.stefan
                image: /local/Stefan_cropped.jpg
                column: 1              
                column_span: 3         
                row: 1
                row_span: 2          
                color: 'hsl(0, 100%, 100%)'    #white
                color_on: 'hsl(0, 100%, 100%)'    #white
                color_off: 'hsl(0, 100%, 100%)'    #white
                text_size: '1.2em'
                #secondary label
                # label_sec_state: sensor.andrew_occupancy_template
                text_sec_color: "#eee"
                text_sec_size: '0.7em'
                more_info: device_tracker.stefan

              - entity: device_tracker.isabella
                label_state: device_tracker.isabella
                image: /local/Isa_cropped.jpg
                column: 4              
                column_span: 3         
                row: 1             
                row_span: 2       
                color: 'hsl(0, 100%, 100%)'    #white
                color_on: 'hsl(0, 100%, 100%)'    #white
                color_off: 'hsl(0, 100%, 100%)'    #white
                text_size: '1.2em'
                #secondary label
                # label_sec_state: sensor.wife_occupancy_template
                text_sec_color: "#eee"
                text_sec_size: '0.7em'
                more_info: device_tracker.isabella

              - entity: lock.ytterdorr
                label: Lock
                column: 1              
                column_span: 3         
                row: 3             
                row_span: 1          
                color: 'hsl(192, 96%, 48%)'    #blue
                color_on: 'hsl(37, 96%, 48%)'  #orange
                color_off: 'hsl(192, 96%, 48%)'    #blue     
                #secondary label
                label_sec_template: "return state_time;"
                text_sec_color: "#eee"
                text_sec_size: '0.7em'
                icon_size: 18px

              - entity: switch.roomba
                label: Roomba
                column: 4         
                column_span: 3     
                row: 3              
                row_span: 1
                color: 'hsl(192, 96%, 48%)'    #blue
                color_on: 'hsl(37, 96%, 48%)'  #orange
                color_off: 'hsl(192, 96%, 48%)'    #blue 
                #secondary label
                label_sec_template: "return entities['switch.roomba'].attributes.status;"
                text_sec_color: "#eee"
                text_sec_size: '0.7em'
                text_sec_align: right  

              - entity: light.inside_lights
                label: Inside
                icon: mdi:lightbulb-outline  
                more_info: group.inside_lights_automations
                column: 1              
                column_span: 2      
                row: 4      
                row_span: 1         
                color: 'hsl(0, 0%, 80%)'    #grey        
                color_on: 'hsl(37, 96%, 48%)'  #orange
                color_off: 'hsl(0, 0%, 80%)'    #grey 
                icon_size: 18px
                label_sec_template: "return state_time;"
                text_sec_color: "#eee"
                text_sec_size: '0.7em'

              - entity: light.outdoor_lights
                label: Outdoor
                icon: mdi:lightbulb-outline
                more_info: light.outdoor_lights
                column: 3              
                column_span: 2        
                row: 4             
                row_span: 1          
                color: 'hsl(0, 0%, 80%)'    #grey        
                color_on: 'hsl(37, 96%, 48%)'  #orange
                color_off: 'hsl(0, 0%, 80%)'    #grey 
                icon_size: 18px  
                label_sec_template: "return state_time;"
                text_sec_color: "#eee"
                text_sec_size: '0.7em'  

              - entity: light.outdoor_lights
                label: Outdoor
                icon: mdi:lightbulb-outline
                column: 5              
                column_span: 2        
                row: 4            
                row_span: 1      
                color: 'hsl(0, 0%, 80%)'    #grey        
                color_on: 'hsl(37, 96%, 48%)'  #orange
                color_off: 'hsl(0, 0%, 80%)'    #grey  
                icon_size: 18px
                label_sec_template: "return state_time;"
                text_sec_color: "#eee"
                text_sec_size: '0.7em'

              - entity: input_boolean.guest_mode
                label: Guest Mode
                column: 1              
                column_span: 6         
                row: 5             
                row_span: 1        
                color: 'hsla(0, 100%, 100%, 0)'    #white
                color_on: 'hsla(0, 100%, 100%, 0)'    #white
                color_off: 'hsla(0, 100%, 100%, 0)'    #white 
                text_color_on: 'hsl(192, 96%, 48%)'    #blue
                text_color_off: 'hsl(192, 96%, 48%)'    #blue
                hide_when_off: 'true'
                label_sec_template: "return state_time;"
                text_sec_color: "#aaa"
                text_sec_size: '0.7em'
                more_info: input_boolean.guest_mode

input_text:
  dummy_tiles_main:
    name: Main tiles

group:
  ios_default_view:
    control: hidden
    icon: mdi:apple
    view: yes
    entities:
      - input_text.dummy_tiles_main