homeassistant:

automation:
  - alias: Lights On Outdoor And Hallway At Sunset
    initial_state: 'off'
    trigger:
      platform: sun
      event: sunset
      offset: "-00:45:00"
    action:
      - service: scene.turn_on
        entity_id: scene.lights_at_dark

  - alias: Lights Off Outdoor And Hallway At 00 Weekday
    initial_state: 'off'
    trigger:
      platform: time
      at: '23:59:00'
    condition:
      condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - sun
    action:
      - service: light.turn_off
        data:
          entity_id: light.outdoor_front_light
          transition: 30
      - service: light.turn_off
        data:
          entity_id: light.outdoor_yard_light
          transition: 30
      - service: light.turn_off
        data:
          entity_id: light.hallway_window_light
          transition: 30
      - service: light.turn_off
        entity_id: light.outdoor_hanging_lights
        
  - alias: Lights Off Outdoor And Hallway At 00 Weekend
    initial_state: 'off'
    trigger:
      platform: time
      at: '23:59:00'
    condition:
      - condition: time
        weekday:
          - fri
          - sat
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
    action:
      - service: light.turn_off
        data:
          entity_id: light.outdoor_front_light
          transition: 30
      - service: light.turn_off
        data:
          entity_id: light.outdoor_yard_light
          transition: 30
      - service: light.turn_off
        data:
          entity_id: light.hallway_window_light
          transition: 30
      - service: light.turn_off
        entity_id: light.outdoor_hanging_lights