homeassistant:
  customize:
    input_text.lights_tiles:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 6
        # column_width: 50px
        # row_height: 50px
        # gap: 15px
        color: '#555B65'
        color_on: '#D5D619'
        color_off: '#BBBEC2'
        entities:
          - entity: script.goodnight
            # label: S1
            column: 1
            row: 1
            # row_span: 1
            # column_span: 1
            icon: mdi:hotel
          - entity: script.goodmorning
            # label: S1
            column: 2
            row: 1
            icon: mdi:kettle
          - entity: script.movie_time
            # label: S1
            column: 3
            row: 1
            icon: mdi:television-classic
            
    script.movie_time:
      homebridge_visible: true
      homebridge_name: Movie Time

    group.outdoor_lights:
      homebridge_visible: true
      homebridge_name: Outdoor Lights
      
    group.inside_lights_automations:
      homebridge_visible: true
      homebridge_name: All Lights

    light.gateway_light_34ce008bfc4b:
      friendly_name: Nightlight
      homebridge_visible: true
      homebridge_name: Nightlight

    # light.living_room_ceiling_light_level:
    #   icon: mdi:sofa
    #   friendly_name: Living Room Light
    #   homebridge_visible: true     
    #   homebridge_name: Living Room Ceiling Light
        
    # light.upstairs_hallway_ceiling_light_level:
    #   icon: mdi:ceiling-light
    #   friendly_name: Upstairs Hallway Light
    #   homebridge_visible: true     
    #   homebridge_name: Upstairs Hallway Light
        
    # light.dining_area_ceiling_light_level:
    #   friendly_name: Dining Room Light
    #   icon: mdi:silverware-variant
    #   homebridge_visible: true     
    #   homebridge_name: Dining Room Light
        
    # light.passage_ceiling_spotlights_level:
    #   friendly_name: Passage Lights
    #   icon: mdi:spotlight-beam
    #   homebridge_visible: true     
    #   homebridge_name: Passage Lights
        
    # light.living_room_spotlights_level:
    #   friendly_name: Living room Spotlights
    #   icon: mdi:book-open-page-variant
    #   homebridge_visible: true     
    #   homebridge_name: Living room Spotlights
        
    # light.isa_ceiling_light:
    #   friendly_name: Isa Ceiling Light
    #   icon: mdi:human-female
    #   homebridge_visible: true     
    #   homebridge_name: Isa Light

    # light.bedroom_ceiling_light:
    #   friendly_name: Bedroom Ceiling Light
    #   icon: mdi:hotel
    #   homebridge_visible: true     
    #   homebridge_name: Bedroom Light

    # light.bedside_lamp:
    #   friendly_name: Bedside Lamp
    #   icon: mdi:hotel
    #   homebridge_visible: true     
    #   homebridge_name: Bedside Lamp

    # light.floorlamp_uplight:
    #   icon: mdi:floor-lamp
    #   friendly_name: Floorlamp
    #   homebridge_visible: true     
    #   homebridge_name: Floorlamp
        
    # light.floorlamp_reading_light:
    #   icon: mdi:lamp
    #   friendly_name: Floorlamp Reading Light
    #   homebridge_visible: true     
    #   homebridge_name: Floorlamp Reading Light

    # light.stefan_lightstrip:
    #   confirm_controls_show_lock: true
    #   state_card_mode: no-slider
    #   homebridge_visible: true
    #   homebridge_name: Stefan Lightstrip
    #   icon: mdi:led-strip
            
    # light.kitchen_ceiling_spotlights_level:
    #   icon: mdi:fridge
    #   friendly_name: Kitchen Lights
    #   homebridge_visible: true
    #   homebridge_name: Kitchen Lights


input_text:
  lights_tiles:
    name: Lights

script:
  movie_time:
    alias: Movie Time
    sequence:
      - service: light.turn_off
        data:
          entity_id: light.living_room_spotlights_level, light.passage_ceiling_spotlights_level, light.kitchen_ceiling_spotlights_level, light.dining_area_ceiling_light_level, light.floorlamp_reading_light, light.floorlamp_uplight, light.isa_ceiling_light
          transition: 30
      - service: light.turn_on
        data:
          entity_id: light.living_room_ceiling_light_level, group.stairs_lights, light.upstairs_hallway_ceiling_light_level
          brightness: 10

light:
  - platform: lifx
  - platform: group
    name: 'Outdoor lights'
    entities:
      - light.outdoor_plug
      - light.outdoor_front_light
      - light.outdoor_yard_light


group:
  lights:
    control: hidden
    name: Inside lights
    entities:
      - input_text.lights_tiles
      # - group.outdoor_lights_card
      - light.outdoor_lights
      - light.bedroom_ceiling_light
      - light.bedside_lamp
      - light.dining_area_ceiling_light_level  
      - light.kitchen_ceiling_spotlights_level
      - light.floorlamp_reading_light
      - light.christmas_candelabra
      - light.storage_christmas_candelabra
      - light.floorlamp_uplight
      - light.hallway_window_light
      - light.isa_ceiling_light
      - light.living_room_ceiling_light_level
      - light.living_room_spotlights_level
      - light.passage_ceiling_spotlights_level
      - group.stairs_lights
      - group.walk_in_closet_lights
      # - light.stefan_ceiling_light
      - light.stefan_lightstrip
      - light.upstairs_hallway_ceiling_light_level
      - light.gateway_light_34ce008bfc4b

# for automations, hubby doesn't like his lights to be included
  inside_lights_automations:
    name: Inside Lights Without Stefan
    entities:
      - light.bedroom_ceiling_light
      - light.bedside_lamp
      - light.living_room_ceiling_light_level
      - light.living_room_spotlights_level
      - light.passage_ceiling_spotlights_level
      - light.upstairs_hallway_ceiling_light_level
      - light.dining_area_ceiling_light_level
      - light.isa_ceiling_light
      - light.floorlamp_reading_light
      - light.floorlamp_uplight
      - light.gateway_light_34ce008bfc4b
      - light.kitchen_sink_light
      - group.stairs_lights
      - group.walk_in_closet_lights
      - light.kitchen_ceiling_spotlights_level