homeassistant:

automation:
## Lights on in morning if sun below horizon
  - alias: 'Lights On Outside And Hallway At 06:40 If Before Sunrise'
    trigger:
      platform: time
      at: '06:40:00'
    condition:
      condition: sun
      before: sunrise
    action:
      - service: scene.turn_on
        entity_id: scene.lights_at_dark
      # - service: light.turn_on
      #   entity_id: light.outside_front_light
      #   data:
      #     brightness: 127
      # - service: light.turn_on
      #   entity_id: light.outside_yard_light
      #   data:
      #     brightness: 127
      # - service: light.turn_on
      #   entity_id: light.hallway_window_light
      #   data:
      #     brightness: 45
      # - service: light.turn_on
      #   entity_id: light.outside_yard_hanging_lights

  ## Lights off at sunrise
  - alias: Lights Off Outside And Hallway At Sunrise
    trigger:
      platform: sun
      event: sunrise
    action:
      - service: homeassistant.turn_off
        entity_id: light.outside_front_light
      - service: homeassistant.turn_off
        entity_id: light.outside_yard_light
      - service: homeassistant.turn_off
        entity_id: light.hallway_window_light
      - service: light.turn_off
        entity_id: light.outside_yard_hanging_lights