homeassistant:
  customize:
    light.stairs_bottom_spot:
      icon: mdi:spotlight-beam
    light.stairs_top_spot:
      icon: mdi:spotlight-beam

    binary_sensor.motion_sensor_158d000165ff1f:
      friendly_name: Pir 1
    sensor.illumination_158d000165ff1f:
      friendly_name: Pir 1 lux      
    binary_sensor.motion_sensor_158d0001a66256:
      friendly_name: Pir 2
    sensor.illumination_158d0001a66256:
      friendly_name: Pir 2 lux
   
automation:
  - alias: 'Stairs auto light'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d000165ff1f
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d0001a66256
        to: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.stairs_bottom_spot
          brightness: 100
          rgb_color:
            - 255
            - 147
            - 41
      - service: light.turn_on
        data:
          entity_id: light.stairs_top_spot
          brightness: 100
          rgb_color:
            - 255
            - 147
            - 41
      - delay:
          seconds: 120
      - service: light.turn_off
        entity_id: light.stairs_bottom_spot
      - service: light.turn_off
        entity_id: light.stairs_top_spot