homeassistant:
  customize:
    light.stairs_bottom_spot:
      icon: mdi:spotlight-beam
      friendly_name: Stairs Bottom Spot
      emulated_hue_hidden: false
    light.stairs_top_spot:
      friendly_name: Stairs Top Spot
      icon: mdi:spotlight-beam
      emulated_hue_hidden: false

    binary_sensor.motion_sensor_158d000165ff1f:
      friendly_name: Stairs Bottom
    sensor.illumination_158d000165ff1f:
      friendly_name: Stairs Bottom Lux      
    group.stairs_lights:
      friendly_name: Stairs Lights
      emulated_hue_hidden: false
# automation:
#   - alias: 'Stairs auto light'
#     initial_state: 'off'
#     trigger:
#       - platform: state
#         entity_id: binary_sensor.motion_sensor_158d000165ff1f
#         to: 'on'
#       - platform: state
#         entity_id: binary_sensor.motion_sensor_158d0001a66256
#         to: 'on'
#     action:
#       - service: light.turn_on
#         data:
#           entity_id: light.stairs_bottom_spot
#           brightness: 100
#           rgb_color:
#             - 255
#             - 214
#             - 170
#       - service: light.turn_on
#         data:
#           entity_id: light.stairs_top_spot
#           brightness: 100
#           rgb_color:
#             - 255
#             - 214
#             - 170
#       - delay:
#           seconds: 120
#       - service: light.turn_off
#         entity_id: light.stairs_bottom_spot
#       - service: light.turn_off
#         entity_id: light.stairs_top_spot