homeassistant:
  # customize_glob:
  #   light.*:
  #     state_card_mode: break-slider
  #     stretch_slider: true
  #     slider_theme:
  #       pin: true
  #     confirm_controls: true
  customize:
    light.hallway_window_light:
      icon: mdi:lamp

    light.outdoor_lights:
      icon: mdi:wall-sconce
      
    light.gateway_light_34ce008bfc4b:
      friendly_name: Nightlight
      icon: mdi:lamp

    light.living_room_ceiling_light_level:
      icon: mdi:ceiling-light
      friendly_name: Living Room Light
        
    light.upstairs_hallway_ceiling_light_level:
      icon: mdi:ceiling-light
      friendly_name: Upstairs Hallway Light
        
    light.dining_area_ceiling_light_level:
      friendly_name: Dining Room Light
      icon: mdi:ceiling-light
        
    light.passage_ceiling_spotlights_level:
      friendly_name: Passage Lights
      icon: mdi:track-light
        
    light.living_room_spotlights_level:
      friendly_name: Living room Spotlights
      icon: mdi:track-light
        
    light.isa_ceiling_light:
      friendly_name: Isa Ceiling Light
      icon: mdi:ceiling-light

    light.bedroom_ceiling_light:
      friendly_name: Bedroom Ceiling Light
      icon: mdi:ceiling-light

    light.bedside_lamp:
      friendly_name: Bedside Lamp
      icon: mdi:lamp

    light.floorlamp_uplight:
      icon: mdi:floor-lamp
      friendly_name: Floorlamp
        
    light.floorlamp_reading_light:
      icon: mdi:lamp
      friendly_name: Floorlamp Reading Light

    light.stefan_lightstrip:
      icon: mdi:led-strip
            
    light.kitchen_ceiling_spotlights_level:
      icon: mdi:track-light
      friendly_name: Kitchen Lights

    light.outdoor_front_light:
      icon: mdi:wall-sconce
      
    light.outdoor_hanging_lights:
      icon: mdi:lightbulb

    light.outdoor_yard_light:
      icon: mdi:wall-sconce

    light.walk_in_closet_lights:
      icon: mdi:wall-sconce

script:
  movie_time:
    alias: Movie Time
    sequence:
      - service: light.turn_off
        data:
          entity_id: light.living_room_spotlights_level, light.passage_ceiling_spotlights_level, light.kitchen_ceiling_spotlights_level, light.dining_area_ceiling_light_level, light.floorlamp_reading_light, light.floorlamp_uplight, light.isa_ceiling_light
          transition: 30
      - service: light.turn_on
        data:
          entity_id: light.living_room_ceiling_light_level, light.stairs_lights_lights, light.upstairs_hallway_ceiling_light_level
          brightness: 10
          
  occusim_stefan_on:
    alias: Occusim Stefan On
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.stefan_lightstrip
          brightness: 255
          color_temp: 153

  occusim_stefan_normal:
    alias: Occusim Stefan Normal
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.stefan_lightstrip
          brightness: 200
          rgb_color:
            - 70
            - 255
            - 236

  dark_lights_off:
    alias: Dark Lights Off
    sequence:
      - service: light.turn_off
        data:
          entity_id: light.outdoor_front_light
          transition: 30
      - service: light.turn_off
        data:
          entity_id: light.outdoor_yard_light
          transition: 30
      - service: light.turn_off
        data:
          entity_id: light.hallway_window_light
          transition: 30
      - service: light.turn_off
        entity_id: light.outdoor_hanging_lights

light:
  - platform: rfxtrx
    signal_repetitions: 3
    devices:
      0b11000273bc0cfe08010f70:
        name: Outdoor hanging lights
      0b11000382bc0cfe00010f70:
        name: Outdoor front hanging lights
  - platform: lifx
  - platform: group
    name: 'Outdoor lights'
    entities:
      - light.outdoor_plug
      - light.outdoor_front_light
      - light.outdoor_yard_light
      - light.outdoor_hanging_lights
  - platform: group
    name: 'Inside lights'
    entities:
      - light.bedroom_ceiling_light
      - light.bedside_lamp
      - light.living_room_ceiling_light_level
      - light.living_room_spotlights_level
      - light.passage_ceiling_spotlights_level
      - light.upstairs_hallway_ceiling_light_level
      - light.dining_area_ceiling_light_level
      - light.isa_ceiling_light
      - light.floorlamp_reading_light
      - light.floorlamp_uplight
      - light.gateway_light_34ce008bfc4b
      - light.kitchen_sink_light
      - light.stairs_lights
      - light.walk_in_closet_lights
      - light.kitchen_ceiling_spotlights_level

  - platform: group
    name: 'Downstairs lights'
    entities:
      - light.dining_area_ceiling_light_level  
      - light.kitchen_ceiling_spotlights_level
      - light.floorlamp_reading_light
      - light.floorlamp_uplight
      - light.hallway_window_light
      - light.stairs_lights
      - light.passage_ceiling_spotlights_level
      - light.living_room_ceiling_light_level
      - light.living_room_spotlights_level

  - platform: group
    name: 'Upstairs lights'
    entities:
      - light.bedroom_ceiling_light
      - light.bedside_lamp
      - light.isa_ceiling_light
      - light.walk_in_closet_lights
      # - light.stefan_ceiling_light
      # - light.stefan_lightstrip
      - light.upstairs_hallway_ceiling_light_level
      - light.gateway_light_34ce008bfc4b

group:
  lights:
    control: hidden
    name: Lights
    entities:
      - input_text.lights_tiles
      # - group.outdoor_lights_card
      - light.outdoor_lights
      - light.bedroom_ceiling_light
      - light.bedside_lamp
      - light.dining_area_ceiling_light_level  
      - light.kitchen_ceiling_spotlights_level
      - light.floorlamp_reading_light
      - light.christmas_candelabra
      - light.storage_christmas_candelabra
      - light.floorlamp_uplight
      - light.hallway_window_light
      - light.isa_ceiling_light
      - light.living_room_ceiling_light_level
      - light.living_room_spotlights_level
      - light.passage_ceiling_spotlights_level
      - light.stairs_lights_lights
      - light.walk_in_closet_lights
      # - light.stefan_ceiling_light
      - light.stefan_lightstrip
      - light.upstairs_hallway_ceiling_light_level
      - light.gateway_light_34ce008bfc4b

# for automations, without Stefans lights
  inside_lights_automations:
    name: Inside Lights Without Stefan
    entities:
      - light.bedroom_ceiling_light
      - light.bedside_lamp
      - light.living_room_ceiling_light_level
      - light.living_room_spotlights_level
      - light.passage_ceiling_spotlights_level
      - light.upstairs_hallway_ceiling_light_level
      - light.dining_area_ceiling_light_level
      - light.isa_ceiling_light
      - light.floorlamp_reading_light
      - light.floorlamp_uplight
      - light.gateway_light_34ce008bfc4b
      - light.kitchen_sink_light
      - light.stairs_lights
      - light.walk_in_closet_lights
      - light.kitchen_ceiling_spotlights_level