homeassistant:

automation:
## Lights on in morning if sun below horizon
  - alias: 'Lights On Outdoor And Hallway At 06:40 If Before Sunrise'
    trigger:
      platform: time
      at: '06:40:00'
    condition:
      condition: and
      conditions:
        - condition: sun
          before: sunrise
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: state
          entity_id: device_tracker.isabella
          state: 'Home'
    action:
      - service: scene.turn_on
        entity_id: scene.lights_at_dark

  ## Lights off at sunrise
  - alias: Lights Off Outdoor And Hallway At Sunrise
    trigger:
      platform: sun
      event: sunrise
    action:
      - service: homeassistant.turn_off
        entity_id: light.outdoor_front_light
      - service: homeassistant.turn_off
        entity_id: light.outdoor_yard_light
      - service: homeassistant.turn_off
        entity_id: light.hallway_window_light
      - service: light.turn_off
        entity_id: light.outdoor_yard_hanging_lights