homeassistant:
  customize:
    binary_sensor.door_window_sensor_158d00016d7004:
      friendly_name: Mailbox Package Door
    binary_sensor.door_window_sensor_158d00016d6ef9:
      friendly_name: Mailbox Letter Slot
    binary_sensor.switch_158d00016c0a49:
      friendly_name: Mailbox Reset

automation:
  - alias: Mailbox package
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00016d7004
        to: 'on'
    action:
      - service: python_script.mailbox
        data_template:
          state: 'package'
      - service: notify.ios_isabellas_iphone_6s
        data:
          title: 'Package?'
          message: 'You have mail'

  - alias: Mailbox letter
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00016d6ef9
        to: 'on'
    action:
      - service: python_script.mailbox
        data_template:
          state: 'mail'
      - service: notify.ios_isabellas_iphone_6s
        data:
          title: 'Mail!'
          message: 'Someone put a letter in the mailbox'

  - alias: Mailbox Reset
    initial_state: 'on'
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d00016c0a49
        click_type: single
    action:
      - service: python_script.mailbox
        data_template:
          state: 'reset'

  # - alias: Mailbox Reset
  #   initial_state: 'on'
  #   trigger:
  #     - platform: time
  #       at: '23:59:00'
  #   action:
  #     - service: python_script.mailbox
  #       data_template:
  #         state: 'reset'