homeassistant:
  customize:
    binary_sensor.door_window_sensor_158d00016d7004:
      friendly_name: Mailbox Package Door

automation:
  - alias: Mailbox
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d00016d7004
        to: 'on'
    action:
      - service: python_script.mailbox
        data_template:
          state: 'mail'
      - service: notify.ios_isabellas_iphone_6s
        data:
          title: 'Package!'
          message: 'Someone opened the package door'

  - alias: Mailbox Reset
    initial_state: 'on'
    trigger:
      - platform: time
        at: '23:59:00'
    action:
      - service: python_script.mailbox
        data_template:
          state: 'reset'