homeassistant:
  customize:
    binary_sensor.mailbox_package:
      friendly_name: Mailbox Package Door
    binary_sensor.mailbox_letter:
      friendly_name: Mailbox Letter Slot

# automation:
#   - alias: Mailbox package
#     initial_state: 'on'
#     trigger:
#       - platform: state
#         entity_id: binary_sensor.mailbox_package
#         to: 'on'
#     action:
#       # - service: python_script.mailbox
#       #   data_template:
#       #     state: 'package'
#       - service: notify.ios_isabellas_iphone_x
#         data:
#           title: 'Package?'
#           message: 'You have mail'

#   - alias: Mailbox letter
#     initial_state: 'on'
#     trigger:
#       - platform: state
#         entity_id: binary_sensor.mailbox_letter
#         to: 'on'
#     action:
#       # - service: python_script.mailbox
#       #   data_template:
#       #     state: 'mail'
#       - service: notify.ios_isabellas_iphone_x
#         data:
#           title: 'Mail!'
#           message: 'Someone put a letter in the mailbox'

  # - alias: Mailbox Reset
  #   initial_state: 'on'
  #   trigger:
  #     - platform: time
  #       at: '23:59:00'
  #   action:
  #     - service: python_script.mailbox
  #       data_template:
  #         state: 'reset'