homeassistant:
  customize:
    sensor.monstera_temperature:
      homebridge_visible: true
    sensor.palm_temperature:
      homebridge_visible: true


sensor:
  - platform: miflora
    mac: "C4:7C:8D:60:A5:B3"
    name: Monstera
    median: 3
    cache: 10800
    force_update: true
    monitored_conditions:
      - temperature
      - light
      - moisture
      - conductivity
      - battery
  - platform: miflora
    mac: "C4:7C:8D:63:13:9B"
    name: Palm
    median: 3
    cache: 10800
    force_update: true
    monitored_conditions:
      - temperature
      - light
      - moisture
      - conductivity
      - battery

# alert:
#   palm_problem:
#     name: Palm is having a problem
#     entity_id: plant.palm
#     state: 'problem'
#     repeat: 1440 # every 24h
#     can_acknowledge: True
#     notifiers:
#       - ios_isabellas_iphone_6s

#   monstera_problem:
#     name: Monstera is having a problem
#     entity_id: plant.monstera
#     state: 'problem'
#     repeat: 1440 # every 24h
#     can_acknowledge: True
#     notifiers:
#       - ios_isabellas_iphone_6s