homeassistant:
  customize:
    sensor.small_chili_temperature:
      homebridge_visible: true
      icon: mdi:thermometer
    sensor.palm_temperature:
      homebridge_visible: true
      icon: mdi:thermometer      
    sensor.palm_light_intensity:
      icon: mdi:theme-light-dark
    sensor.small_chili_light_intensity:
      icon: mdi:theme-light-dark

group:
  plant_card:
    view: no
    name: Plants
    entities:
      - plant.palm
      - plant.small_chili
      - plant.big_chili

sensor:                
  - platform: mqtt
    state_topic: "homeassistant/sensor/palm_temperature/state"
    name: Palm temperature
    unit_of_measurement: '°C'
  - platform: mqtt
    state_topic: "homeassistant/sensor/big_chili_temperature/state"
    name: Big chili temperature
    unit_of_measurement: '°C'
  - platform: mqtt
    state_topic: "homeassistant/sensor/small_chili_temperature/state"
    name: Small chili temperature
    unit_of_measurement: '°C'

  - platform: mqtt
    state_topic: "homeassistant/sensor/palm_moisture/state"
    name: Palm moisture
    unit_of_measurement: '%'
  - platform: mqtt
    state_topic: "homeassistant/sensor/big_chili_moisture/state"
    name: Big chili moisture
    unit_of_measurement: '%'
  - platform: mqtt
    state_topic: "homeassistant/sensor/small_chili_moisture/state"
    name: Small chili moisture
    unit_of_measurement: '%'

  - platform: mqtt
    state_topic: "homeassistant/sensor/palm_battery/state"
    name: Palm battery
    unit_of_measurement: '%'
  - platform: mqtt
    state_topic: "homeassistant/sensor/big_chili_battery/state"
    name: Big chili battery
    unit_of_measurement: '%'
  - platform: mqtt
    state_topic: "homeassistant/sensor/small_chili_battery/state"
    name: Small chili battery
    unit_of_measurement: '%'

plant:
  palm:
    sensors:
      moisture: sensor.palm_moisture
      battery: sensor.palm_battery
      temperature: sensor.palm_temperature
      # conductivity: sensor.palm_conductivity
      # brightness: sensor.palm_light_intensity
    min_moisture: 20
    max_moisture: 60
    min_battery: 10
    # min_conductivity: 500
    # max_conductivity: 3000

  small_chili:
    sensors:
      moisture: sensor.small_chili_moisture
      battery: sensor.small_chili_battery
      temperature: sensor.small_chili_temperature
      # conductivity: sensor.small_chili_conductivity
      # brightness: sensor.small_chili_light_intensity
    min_moisture: 20
    max_moisture: 60
    min_battery: 10
    # min_conductivity: 500
    # max_conductivity: 3000 

  big_chili:
    sensors:
      moisture: sensor.big_chili_moisture
      battery: sensor.big_chili_battery
      temperature: sensor.big_chili_temperature
      # conductivity: sensor.big_chili_conductivity
      # brightness: sensor.big_chili_light_intensity
    min_moisture: 20
    max_moisture: 60
    min_battery: 10
    # min_conductivity: 500
    # max_conductivity: 3000      