homeassistant:
  customize:
    binary_sensor.motion_sensor_158d000165ff1f:
      friendly_name: Living Room Motion
    binary_sensor.motion_sensor_158d0001a66256:
      friendly_name: Hallway Motion

sensor:
  - platform: template
    sensors:
      passage_movement:
        friendly_name: 'Passage Movement'
        value_template: '{% if is_state("binary_sensor.passage_pir_sensor", "on") %}Movement detected{% else %}No movement{% endif %}'
        icon_template: '{% if is_state("binary_sensor.passage_pir_sensor", "on") %}mdi:run-fast{% else %}mdi:sleep{% endif %}'

      upstairs_hallway_movement:
        friendly_name: 'Upstairs Hallway Movement'
        value_template: '{% if is_state("binary_sensor.upstairs_hallway_pir_sensor", "on") %}Movement detected{% else %}No movement{% endif %}'
        icon_template: '{% if is_state("binary_sensor.upstairs_hallway_pir_sensor", "on") %}mdi:run-fast{% else %}mdi:sleep{% endif %}'    

      living_room_movement:
        friendly_name: 'Living Room Motion'
        value_template: '{% if is_state("binary_sensor.motion_sensor_158d000165ff1f", "on") %}Movement detected{% else %}No movement{% endif %}'
        icon_template: '{% if is_state("binary_sensor.motion_sensor_158d000165ff1f", "on") %}mdi:run-fast{% else %}mdi:sleep{% endif %}'

      hallway_movement:
        friendly_name: 'Hallway Movement'
        value_template: '{% if is_state("binary_sensor.motion_sensor_158d0001a66256", "on") %}Movement detected{% else %}No movement{% endif %}'
        icon_template: '{% if is_state("binary_sensor.motion_sensor_158d0001a66256", "on") %}mdi:run-fast{% else %}mdi:sleep{% endif %}'

  - platform: template
    sensors:
      last_seen_motion:
        friendly_name: 'Last Seen Motion'
        value_template: >
                    {%- set pirs = [states.sensor.passage_movement, states.sensor.upstairs_hallway_movement, states.binary_sensor.motion_sensor_158d000165ff1f, states.binary_sensor.motion_sensor_158d0001a66256] %}
                    {% for pir in pirs %}
                      {% if as_timestamp(pir.last_changed) == as_timestamp(pirs | map(attribute='last_changed') | max) %}
                        {{ pir.name }}
                      {% endif %}
                    {% endfor %}