homeassistant:
  customize:
    sensor.magic_mirror_rpi:
      icon: mdi:raspberrypi
    sensor.hass_rpi:
      icon: mdi:home-assistant      
    sensor.stefan_computer:
      icon: mdi:monitor
      homebridge_hidden: true
    sensor.isa_laptop:
      icon: mdi:laptop-windows
      homebridge_hidden: true
    sensor.isa_computer:
      icon: mdi:monitor
      homebridge_hidden: true
    sensor.asus_router:
      icon: mdi:wifi
      homebridge_hidden: true
    sensor.netgear_router:
      icon: mdi:wifi
      homebridge_hidden: true
    sensor.printer:
      icon: mdi:printer
      homebridge_hidden: true
    sensor.nas:
      icon: mdi:server
      homebridge_hidden: true
    sensor.chromecast:
      icon: mdi:cast
      homebridge_hidden: true
    sensor.shield:
      icon: mdi:android
      homebridge_hidden: true
    sensor.shield_2:
      icon: mdi:android
      homebridge_hidden: true
    sensor.ipad:
      icon: mdi:tablet-ipad
      homebridge_hidden: true
    sensor.movie_system:
      icon: mdi:speaker
      homebridge_hidden: true
    sensor.samsung65:
      icon: mdi:television
      homebridge_hidden: true
    sensor.hue_hub:
      icon: mdi:lightbulb-outline
      homebridge_hidden: true
    sensor.ikea_gateway:
      icon: mdi:google-keep
    sensor.xiaomi_gateway:
      icon: mdi:google-keep
    sensor.ip_camera:
      icon: mdi:webcam
      homebridge_hidden: true
    sensor.galaxy_tab:
      icon: mdi:tablet-android
      homebridge_hidden: true
    sensor.samsung49:
      icon: mdi:television
      homebridge_hidden: true
    sensor.ir_blaster:
      icon: mdi:remote
      homebridge_hidden: true
    sensor.ir_blaster_bedroom:
      icon: mdi:remote
      homebridge_hidden: true
    sensor.ir_blaster_livingroom:
      icon: mdi:remote
      homebridge_hidden: true
    sensor.withings_scale:
      icon: mdi:scale-bathroom
      homebridge_hidden: true
    sensor.sonos_3:
      icon: mdi:speaker-wireless
      homebridge_hidden: true
sensor:
  - platform: template
    sensors:
        nas:
          friendly_name: 'Synology NAS'
          value_template: "{{ 'Online' if is_state('device_tracker.0011325962fb', 'home') else 'Offline' }}"
        samsung65:
          friendly_name: 'Livingroom TV'
          value_template: "{{ 'Online' if is_state('device_tracker.90f1aac2077c', 'home') else 'Offline' }}"
        samsung49:
          friendly_name: 'Bedroom TV'
          value_template: "{{ 'Online' if is_state('device_tracker.14bb6eceb76a', 'home') else 'Offline' }}"
        movie_system:
          friendly_name: 'Home Movie System'
          value_template: "{{ 'Online' if is_state('device_tracker.0c89109204ff', 'home') else 'Offline' }}"
        netgear_router:
          friendly_name: 'Netgear Router'
          value_template: "{{ 'Online' if is_state('device_tracker.204e7f4bf81b', 'home') else 'Offline' }}"
        shield:
          friendly_name: 'NVidia Shield'
          value_template: "{{ 'Online' if is_state('device_tracker.android8e3893d2d746d835', 'home') else 'Offline' }}"
        shield_2:
          friendly_name: 'NVidia Shield 2'
          value_template: "{{ 'Online' if is_state('device_tracker.shield', 'home') else 'Offline' }}"
        chromecast:
          friendly_name: 'Chromecast Bedroom'
          value_template: "{{ 'Online' if is_state('device_tracker.chromecast', 'home') else 'Offline' }}"
        stefan_computer:
          friendly_name: 'Stefan computer'
          value_template: "{{ 'Online' if is_state('device_tracker.grimsan55', 'home') else 'Offline' }}"
        isa_computer:
          friendly_name: 'Isas computer'
          value_template: "{{ 'Online' if is_state('device_tracker.isa', 'home') else 'Offline' }}"
        isa_laptop:
          friendly_name: 'Isas laptop'
          value_template: "{{ 'Online' if is_state('device_tracker.laptopo5pj4rks', 'home') else 'Offline' }}"
        printer:
          friendly_name: 'HP Printer'
          value_template: "{{ 'Online' if is_state('device_tracker.hp16eece', 'home') else 'Offline' }}"
        ipad:
          friendly_name: 'iPad'
          value_template: "{{ 'Online' if is_state('device_tracker.paddan', 'home') else 'Offline' }}"
        galaxy_tab:
          friendly_name: 'Galaxy Tab'
          value_template: "{{ 'Online' if is_state('device_tracker.android8c0fc07d9694a5a2', 'home') else 'Offline' }}"
        hue_hub:
          friendly_name: 'Philips Hue Gateway'
          value_template: "{{ 'Online' if is_state('device_tracker.philipshue', 'home') else 'Offline' }}"
        asus_router:
          friendly_name: 'Asus Router'
          value_template: "{{ 'Online' if is_state('device_tracker.routerasuscom', 'home') else 'Offline' }}"
        ip_camera:
          friendly_name: 'IP Camera'
          value_template: "{{ 'Online' if is_state('device_tracker.00b06c1a907f', 'home') else 'Offline' }}"
        ir_blaster:
          friendly_name: 'Broadlink IR Blaster Hallway'
          value_template: "{{ 'Online' if is_state('device_tracker.broadlink_rmminib2ea6e', 'home') else 'Offline' }}"
        withings_scale:
          friendly_name: 'Withings scale'
          value_template: "{{ 'Online' if is_state('device_tracker.0024e40a2868', 'home') else 'Offline' }}"
        ir_blaster_bedroom:
          friendly_name: 'Broadlink IR Blaster Bedroom'
          value_template: "{{ 'Online' if is_state('device_tracker.broadlink_rmminicce9a4', 'home') else 'Offline' }}"
        ir_blaster_livingroom:
          friendly_name: 'Broadlink IR Blaster Livingroom'
          value_template: "{{ 'Online' if is_state('device_tracker.broadlink_rmminiccec6f', 'home') else 'Offline' }}"
        ikea_gateway:
          friendly_name: 'Ikea Trådfri Gateway'
          value_template: "{{ 'Online' if is_state('device_tracker.gwa0cc2bfd2145', 'home') else 'Offline' }}"
        xiaomi_gateway:
          friendly_name: 'Xiaomi Gateway'
          value_template: "{{ 'Online' if is_state('device_tracker.lumigatewayv3_miio57536510', 'home') else 'Offline' }}"
        sonos:
          friendly_name: 'Sonos'
          value_template: "{{ 'Online' if is_state('device_tracker.sonoszp', 'home') else 'Offline' }}"
        magic_mirror_rpi:
          friendly_name: 'Magic Mirror Rpi'
          value_template: "{{ 'Online' if is_state('device_tracker.raspberrypi_2', 'home') else 'Offline' }}"
        hass_rpi:
          friendly_name: 'Hass Rpi'
          value_template: "{{ 'Online' if is_state('device_tracker.raspberrypi', 'home') else 'Offline' }}"

automation:
  - alias: 'Device Status'
    hide_entity: True
    trigger:
         - platform: state
           entity_id:
             - sensor.asus_router
             - sensor.netgear_router
             - sensor.printer
             - sensor.nas
             - sensor.hue_hub
             - sensor.ir_blaster
             - sensor.ir_blaster_bedroom
             - sensor.ir_blaster_livingroom
             - sensor.xiaomi_gateway
             - sensor.ikea_gateway
           to: 'offline'
           for:
             minutes: 5
    action:
      - service: notify.ios_isabellas_iphone_6s
        data_template:
          title: 'Device {{ trigger.to_state.name }} is'
          message: >
            '{{ trigger.to_state.state }}'