## From https://philhawthorne.com/making-home-assistants-presence-detection-not-so-binary/
homeassistant:
  customize:     
    device_tracker.isabella:
      entity_picture: /local/Isa.jpg
    device_tracker.isabellas_iphone_x_wifi:
      icon: mdi:cellphone-iphone
    device_tracker.isabellas_iphone_x_bt:
      icon: mdi:bluetooth
    device_tracker.stefan:
      entity_picture: /local/Stefan.jpg

group:
  persons:
    view: no
    entities:
      - device_tracker.isabellas_iphone_x
      - device_tracker.isabellas_iphone_x_wifi
      - device_tracker.isabellas_iphone_x_bt
      - device_tracker.stefan_iphone_7_wifi
      - device_tracker.stefan_iphone_7
      - device_tracker.stefan_iphone_7_bt
      - input_boolean.stefan_home
      - input_boolean.isa_home
      
  isabella:
    name: Isabella
    entities:
      - device_tracker.isabellas_iphone_x
      - device_tracker.isabellas_iphone_x_wifi
      - device_tracker.isabellas_iphone_x_bt
  stefan:
    name: Stefan
    entities:
      - device_tracker.stefan_iphone_7_wifi
      - device_tracker.stefan_iphone_7
      - device_tracker.stefan_iphone_7_bt
   
input_boolean:
  isa_home:
    name: Isa Homekit
    initial: on
    # icon: mdi:
  stefan_home:
    name: Stefan Homekit
    initial: on
    # icon: mdi:
  ad_presence:
    name: Appdaemon presence notify
    initial: on

input_select:
  stefan_status_dropdown:
    name: Stefan
    options:
      - Home
      - Homebound
      - Just Arrived
      - Just Left
      - Away
      - Work S
      - Work solna
      - Golf
      - Store
      - Extended Away
    initial: Home

  isa_status_dropdown:
    name: Isa
    options:
      - Home
      - Homebound
      - Just Arrived
      - Just Left
      - Away
      - Work I
      - Golf
      - Store
      - Extended Away
    initial: Home

proximity:
  home_isa: 
    zone: home
    devices:
      - device_tracker.isabellas_iphone_x
    tolerance: 50
    unit_of_measurement: km
  home_stefan: 
    zone: home
    devices:
      - device_tracker.stefan_iphone_7
    tolerance: 50
    unit_of_measurement: km

automation:
  - alias: Presence just arrived
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: group.stefan
        from: 'not_home'
        to: 'home'
      - platform: state
        entity_id: group.isabella
        from: 'not_home'
        to: 'home'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'group.stefan' %}
              input_select.stefan_status_dropdown
            {% else %}
              input_select.isa_status_dropdown
            {% endif %}
          option: >
            {% if trigger.entity_id == 'group.stefan' %}
              {% if states.input_select.stefan_status_dropdown.state == 'Just Left' %}
                Home
              {% else %}
                Just Arrived
              {% endif %}
            {% else %}
              {% if states.input_select.isa_status_dropdown.state == 'Just Left' %}
                Home
              {% else %}
                Just Arrived
              {% endif %}
            {% endif %}

  - alias: Presence home
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.stefan_status_dropdown
        to: 'Just Arrived'
        for:
          minutes: 10
      - platform: state
        entity_id: input_select.isa_status_dropdown
        to: 'Just Arrived'
        for:
          minutes: 10
      - platform: state
        entity_id: input_select.stefan_status_dropdown
        from: 'Just Left'
        to: 'Just Arrived'
      - platform: state
        entity_id: input_select.isa_status_dropdown
        from: 'Just Left'
        to: 'Just Arrived'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'input_select.stefan_status_dropdown' %}
              input_select.stefan_status_dropdown
            {% else %}
              input_select.isa_status_dropdown
            {% endif %}
          option: Home

  - alias: Presence just left
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: group.stefan
        from: 'home'
        to: 'not_home'
      - platform: state
        entity_id: group.isabella
        from: 'home'
        to: 'not_home'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'group.stefan' %}
              input_select.stefan_status_dropdown
            {% else %}
              input_select.isa_status_dropdown
            {% endif %}
          option: Just Left

  - alias: Presence away
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.stefan_status_dropdown
        to: 'Just Left'
        for:
          minutes: 5
      - platform: state
        entity_id: input_select.isa_status_dropdown
        to: 'Just Left'
        for:
          minutes: 5
      - platform: zone
        entity_id: device_tracker.stefan_iphone_7
        zone: zone.work_s
        event: leave
      - platform: zone
        entity_id: device_tracker.isabellas_iphone_x
        zone: zone.work_i
        event: leave
      - platform: zone
        entity_id: device_tracker.stefan_iphone_7
        zone: zone.store
        event: leave
      - platform: zone
        entity_id: device_tracker.isabellas_iphone_x
        zone: zone.store
        event: leave
      - platform: zone
        entity_id: device_tracker.stefan_iphone_7
        zone: zone.golf
        event: leave
      - platform: zone
        entity_id: device_tracker.isabellas_iphone_x
        zone: zone.golf
        event: leave
    action:
      - service: input_select.select_option
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'input_select.stefan_status_dropdown' or trigger.entity_id == 'device_tracker.stefan_iphone_7' %}
              input_select.stefan_status_dropdown
            {% else %}
              input_select.isa_status_dropdown
            {% endif %}
          option: Away

  - alias: Presence extended away
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.stefan_status_dropdown
        to: 'Away'
        for:
          hours: 24
      - platform: state
        entity_id: input_select.isa_status_dropdown
        to: 'Away'
        for:
          hours: 24
    action:
      - service: input_select.select_option
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'input_select.stefan_status_dropdown' %}
              input_select.stefan_status_dropdown
            {% else %}
              input_select.isa_status_dropdown
            {% endif %}
          option: Extended Away

  # - alias: Presence work
  #   trigger:
  #     - platform: zone
  #       entity_id: device_tracker.stefan_iphone_7
  #       zone: zone.work_s
  #       event: enter
  #     - platform: zone
  #       entity_id: device_tracker.isabellas_iphone_x
  #       zone: zone.work_i
  #       event: enter
  #   action:
  #     - service: input_select.select_option
  #       data_template:
  #         entity_id: >
  #           {% if trigger.entity_id == 'device_tracker.stefan_iphone_7' %}
  #             input_select.stefan_status_dropdown
  #           {% else %}
  #             input_select.isa_status_dropdown
  #           {% endif %}
  #         option: Work

  # - alias: Presence golf
  #   trigger:
  #     - platform: zone
  #       entity_id: device_tracker.stefan_iphone_7
  #       zone: zone.golf
  #       event: enter
  #     - platform: zone
  #       entity_id: device_tracker.isabellas_iphone_x
  #       zone: zone.golf
  #       event: enter
  #   action:
  #     - service: input_select.select_option
  #       data_template:
  #         entity_id: >
  #           {% if trigger.entity_id == 'device_tracker.stefan_iphone_7' %}
  #             input_select.stefan_status_dropdown
  #           {% else %}
  #             input_select.isa_status_dropdown
  #           {% endif %}
  #         option: Golf

  # - alias: Presence store
  #   trigger:
  #     - platform: zone
  #       entity_id: device_tracker.stefan_iphone_7
  #       zone: zone.store
  #       event: enter
  #     - platform: zone
  #       entity_id: device_tracker.isabellas_iphone_x
  #       zone: zone.store
  #       event: enter
  #   action:
  #     - service: input_select.select_option
  #       data_template:
  #         entity_id: >
  #           {% if trigger.entity_id == 'device_tracker.stefan_iphone_7' %}
  #             input_select.stefan_status_dropdown
  #           {% else %}
  #             input_select.isa_status_dropdown
  #           {% endif %}
  #         option: Store

  - alias: Presence zones
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.isabellas_iphone_x
        to: 'Work I'
      - platform: state
        entity_id: device_tracker.stefan_iphone_7
        to: 'Work S'
      - platform: state
        entity_id: device_tracker.stefan_iphone_7, device_tracker.isabellas_iphone_x
        to: 'Store'
      - platform: state
        entity_id: device_tracker.stefan_iphone_7, device_tracker.isabellas_iphone_x
        to: 'Golf'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'device_tracker.stefan_iphone_7' %}
              input_select.stefan_status_dropdown
            {% else %}
              input_select.isa_status_dropdown
            {% endif %}
          option: "{{ trigger.to_state.state | title }}"
      - service: notify.ios_isabellas_iphone_x
        data_template:
          title: "{{ trigger.to_state.name | title }}"
          message: "{{ trigger.to_state.state | title }}"

  - alias: Presence Homebound
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: proximity.home_isa
        below: 4
      - platform: numeric_state
        entity_id: proximity.home_stefan
        below: 4
    condition:
      condition: and
      conditions:
      - condition: template
        value_template: '{{ states.proximity.home_stefan.attributes.dir_of_travel == "towards" }}'
    action:
      - service: notify.ios_isabellas_iphone_x
        data_template:
          title: "{{ trigger.to_state.name | title }}"
          message: "{{ trigger.to_state.state }}"


  - alias: Presence update tracker
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.stefan_status_dropdown
      - platform: state
        entity_id: input_select.isa_status_dropdown
    action:
      - service: python_script.device_tracker
        data_template:
          entity_id: '{{trigger.entity_id}}'
          meta_entity: >
            {% if trigger.entity_id == 'input_select.stefan_status_dropdown' %}
              Stefan
            {% else %}
              Isabella
            {% endif %}