homeassistant:
  customize:
    input_boolean.stefan_home:
      homebridge_visible: true
      confirm_controls_show_lock: true

input_boolean:
  stefan_home:
    name: Stefan homekit
    initial: on
    icon: mdi:human-male

# Lots of automations to keep track of device tracking works or not        
automation:
  - alias: "Presence Stefan Home By Script"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.stefan_home
        to: 'on'
      - platform: state
        entity_id: device_tracker.stefan_iphone_7, device_tracker.stefan_iphone_7_wifi
        to: 'home'
    action:
      - service: python_script.meta_device_tracker
        data_template:
          entity_id: '{{trigger.entity_id}}'
          meta_entity: 'Stefan'

  - alias: "Presence Stefan Away By Script"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.stefan_home
        to: 'off'
      - platform: state
        entity_id: device_tracker.stefan_iphone_7, device_tracker.stefan_iphone_7_wifi
        to: 'not_home'
    action:
      - service: python_script.meta_device_tracker
        data_template:
          entity_id: '{{trigger.entity_id}}'
          meta_entity: 'Stefan'
          
  - alias: "Presence Stefan Home Notification"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.stefan
        to: 'home'
    action:
      - service: notify.ios_isabellas_iphone_6s
        data:
          title: 'Stefan'
          message: 'home'
  - alias: "Presence Stefan Away Notification"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.stefan
        to: 'not_home'
    action:
      - service: notify.ios_isabellas_iphone_6s
        data:
          title: 'Stefan'
          message: 'not home'