homeassistant:
  customize:
    input_boolean.isabella_home:
      homebridge_visible: true
      confirm_controls_show_lock: true
      homebridge_name: Isabella home
      

input_boolean:
  isabella_home:
    name: Isabella homekit
    initial: on
    icon: mdi:human-female

group:
  isabella:
    name: Isabella
    entities:
      - device_tracker.isabellas_iphone_6s
      - device_tracker.isabellas_iphone_6s_wifi
      - device_tracker.isabellas_iphone_6s_bt
      - device_tracker.isa_computer
      - device_tracker.isa_laptop
      - input_boolean.isabella_home
  persons:
    view: no
    entities:
      - device_tracker.stefan
      - device_tracker.isabella

# Lots of automations to keep track of device tracking works or not
automation:
  - alias: "Presence Isa Home By Script"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.isabella_home
        to: 'on'
      - platform: state
        entity_id: device_tracker.isabellas_iphone_6s, device_tracker.isabellas_iphone_6s_wifi, device_tracker.isabellas_iphone_6s_bt
        to: 'home'
    action:
      - service: python_script.meta_device_tracker
        data_template:
          entity_id: '{{trigger.entity_id}}'
          meta_entity: 'Isabella'

  - alias: "Presence Isa Away By Script"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.isabella_home
        to: 'off'
      - platform: state
        entity_id: device_tracker.isabellas_iphone_6s, device_tracker.isabellas_iphone_6s_wifi, device_tracker.isabellas_iphone_6s_bt
        to: 'not_home'
    action:
      - service: python_script.meta_device_tracker
        data_template:
          entity_id: '{{trigger.entity_id}}'
          meta_entity: 'Isabella'

  - alias: "Presence Isa Home Notification"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.isabella
        to: 'home'
    action:
      - service: notify.ios_isabellas_iphone_6s
        data:
          title: 'Isa'
          message: 'home'
  - alias: "Presence Isa Away Notification"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.isabella
        to: 'not_home'
    action:
      - service: notify.ios_isabellas_iphone_6s
        data:
          title: 'Isa'
          message: 'not home'