homeassistant:
  customize:
    input_boolean.stefan_home:
      homebridge_visible: true

input_boolean:
  stefan_home:
    name: Stefan homekit
    initial: on
    icon: mdi:human-male

binary_sensor:
  - platform: 'bayesian'
    prior: 0.65  # 65 % chance Stefan's at home at any given point
    name: 'Stefan Home Bay'
    probability_threshold: 0.95
    observations:
        # Stefan Home -> likely ios app reports him as home        
      - entity_id: 'device_tracker.stefan_iphone_7'
        prob_given_true: 0.8
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'home'
        # Stefan Home -> likely wifi reports him as home
      - entity_id: 'device_tracker.igrims'
        prob_given_true: 0.7
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'home'
        # Stefan Home -> Very likely his computer is on, but sometimes he leaves it on
      - entity_id: 'device_tracker.grimsan55'
        prob_given_true: 0.99
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
        # Stefan Home -> Very likely Homekit reports him as home
      - entity_id: 'input_boolean.stefan_home'
        prob_given_true: 0.99
        prob_given_false: 0.01
        platform: 'state'
        to_state: 'on'
        # Stefan Home -> likely some inside lights are on
      - entity_id: group.inside_lights_card
        platform: 'state'
        to_state: 'on'
        prob_given_true: 0.7
        

history_graph:
  stefan:
    name: Stefan
    refresh: 180
    entities:
      - device_tracker.stefan_iphone_7
      - device_tracker.igrims
      - device_tracker.grimsan55
      - input_boolean.stefan_home
      - binary_sensor.stefan_home 


# Lots of automations to keep track of device tracking works or not        
automation:
  - alias: "Presence Stefan Homekit Home Mode"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.stefan_home
        to: 'on'
    action:
      - service: notify.ios_isabellas_iphone_6s
        data:
          title: 'Stefan homekit home'
          message: 'wow'

  - alias: "Presence Stefan Homekit Away Mode"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.stefan_home
        to: 'off'
    action:
      - service: notify.ios_isabellas_iphone_6s
        data:
          title: 'Stefan homekit away'
          message: 'wow'

  - alias: 'Presence Stefan Ios Away'
    trigger:
      - platform: state
        entity_id: device_tracker.stefan_iphone_7
        to: 'not_home'
    action:
      - service: notify.ios_isabellas_iphone_6s
        data:
          title: 'Stefan 채r nu rapporterad som inte hemma.'
          message: 'Inte hemma'

  - alias: 'Presence Stefan Ios Home'
    trigger:
      - platform: state
        entity_id: device_tracker.stefan_iphone_7
        to: 'home'
    action:
      - service: notify.ios_isabellas_iphone_6s
        data:
          title: 'Stefan 채r nu rapporterad som hemma.'
          message: 'Hemma'
  ###############################################################


  - alias: 'Presence Stefan Bayesian Home'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.stefan_home
        to: 'on'
    action:
      - service: notify.ios_isabellas_iphone_6s
        data:
          title: 'Stefan 채r nu rapporterad som hemma.'
          message: 'via bayesian'

  - alias: 'Presence Stefan Bayesian Away'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.stefan_home
        to: 'off'
    action:
      - service: notify.ios_isabellas_iphone_6s
        data:
          title: 'Stefan 채r nu rapporterad som inte hemma.'
          message: 'via bayesian'
