
binary_sensor:
  - platform: ring
sensor:
  - platform: ring
camera:
  - platform: ring

group:
  ring_front_door:
    name: Front Door
    # control: hidden
    entities:
      - camera.front_door
      - binary_sensor.ring_front_door_ding
      - binary_sensor.ring_front_door_motion
      - sensor.ring_front_door_last_activity
      - sensor.ring_front_door_last_ding
      - sensor.ring_front_door_last_motion
      - sensor.ring_front_door_volume
      - sensor.ring_front_door_wifi_signal_category
      - sensor.ring_front_door_wifi_signal_strength
      - sensor.ring_front_door_battery      