homeassistant:
  customize:
    camera.front_door:
      friendly_name: Latest Capture Front Door Outdoor
      

binary_sensor:
  - platform: ring
sensor:
  - platform: ring
  - platform: template
    sensors:
      front_door_outdoor_movement:
        friendly_name: 'Front Door Outdoor Movement'
        value_template: '{% if is_state("binary_sensor.ring_front_door_motion", "on") %}Movement detected{% else %}No movement{% endif %}'
        icon_template: '{% if is_state("binary_sensor.ring_front_door_motion", "on") %}mdi:run-fast{% else %}mdi:sleep{% endif %}'
      front_door_latest_ding:
        friendly_name: 'Front Door Latest Ding'
        value_template: '{{ as_timestamp(states.sensor.ring_front_door_last_ding.attributes.created_at) | timestamp_custom("%Y-%m-%d %H:%M") }}'
        icon_template: '{% if is_state("binary_sensor.ring_front_door_ding", "on") %}mdi:bell-ring-outline{% else %}mdi:bell-outline{% endif %}'
      front_door_latest_motion:
        friendly_name: 'Front Door Latest Motion'
        value_template: '{{ as_timestamp(states.sensor.ring_front_door_last_motion.attributes.created_at) | timestamp_custom("%Y-%m-%d %H:%M") }}'
        icon_template: '{% if is_state("binary_sensor.ring_front_door_motion", "on") %}mdi:bell-ring-outline{% else %}mdi:bell-outline{% endif %}'

camera:
  - platform: ring

group:
  ring_front_door:
    name: Front Door
    # control: hidden
    entities:
      - camera.front_door
      - binary_sensor.ring_front_door_ding
      - binary_sensor.ring_front_door_motion
      - sensor.ring_front_door_last_activity
      - sensor.ring_front_door_last_ding
      - sensor.ring_front_door_last_motion
      - sensor.ring_front_door_volume
      - sensor.ring_front_door_wifi_signal_category
      - sensor.ring_front_door_wifi_signal_strength
      - sensor.ring_front_door_battery      

automation:
  - alias: Ring Doorbell Ding Lights
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.ring_front_door_ding
        to: 'on'
    condition:
      - condition: sun
        after: sunset
        after_offset: "-00:45:00"
    action:
      - service: python_script.brighten_then_restore
        data_template:
          entity_id: 'light.outdoor_front_light'
      - service: python_script.brighten_then_restore
        data_template:
          entity_id: 'light.hallway_window_light'

  - alias:  Ring Doorbell Motion Lights
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.ring_front_door_motion
        to: 'on'
    condition:
      - condition: sun
        after: sunset
        after_offset: "-00:45:00"
    action:
      - service: python_script.brighten_then_restore
        data_template:
          entity_id: 'light.outdoor_front_light'
      - service: python_script.brighten_then_restore
        data_template:
          entity_id: 'light.hallway_window_light'

  - alias: Ring Doorbell Low Battery
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: 'sensor.ring_front_door_battery'
        below: '15'
    action:
      - service: notify.ios_isabellas_iphone_x
        data:
          title: 'Ring Doorbell'
          message: 'Low Battery'

  - alias: Ring Doorbell Disconnected
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: 'device_tracker.ring'
        to: 'not_home'
    action:
      - service: notify.ios_isabellas_iphone_x
        data:
          title: 'Ring Doorbell'
          message: 'Disconnected from wifi'

  - alias: Ring Doorbell Connected
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: 'device_tracker.ring'
        to: 'home'
    action:
      - service: notify.ios_isabellas_iphone_x
        data:
          title: 'Ring Doorbell'
          message: 'Connected to wifi'

  - alias: Ring Doorbell Flash Lights
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.ring_front_door_ding
        to: 'on'
    action:
      ## See script here: https://github.com/isabellaalstrom/HomeAssistantConfiguration/blob/master/python_scripts/flash_lights_upstairs_hallway_and_yard.py
      - service: python_script.flash_lights_upstairs_hallway_and_yard