homeassistant:
  customize:
    camera.front_door:
      friendly_name: Last Motion Front Door
      

binary_sensor:
  - platform: ring
sensor:
  - platform: ring
  - platform: template
    sensors:
      front_door_outdoor_movement:
        friendly_name: 'Front Door Outdoor Movement'
        value_template: '{% if is_state("binary_sensor.ring_front_door_motion", "on") %}Movement detected{% else %}No movement{% endif %}'
        icon_template: '{% if is_state("binary_sensor.ring_front_door_motion", "on") %}mdi:run-fast{% else %}mdi:sleep{% endif %}'
      # front_door_latest_ding:
      #   friendly_name: 'Front Door Latest Ding'
      #   value_template: '{{ as_timestamp(states.sensor.ring_front_door_last_ding.attributes.created_at) | timestamp_custom("%Y-%m-%d %H:%M") }}'
      #   icon_template: '{% if is_state("binary_sensor.ring_front_door_ding", "on") %}mdi:bell-ring-outline{% else %}mdi:bell-outline{% endif %}'
      # front_door_latest_motion:
      #   friendly_name: 'Front Door Latest Motion'
      #   value_template: '{{ as_timestamp(states.sensor.ring_front_door_last_motion.attributes.created_at) | timestamp_custom("%Y-%m-%d %H:%M") }}'
      #   icon_template: '{% if is_state("binary_sensor.ring_front_door_motion", "on") %}mdi:bell-ring-outline{% else %}mdi:bell-outline{% endif %}'

camera:
  - platform: ring

automation:
  - alias: Ring Doorbell Low Battery
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: 'sensor.ring_front_door_battery'
        below: '15'
    action:
      - service: notify.ios_isabellas_iphone_x
        data:
          title: 'Ring Doorbell'
          message: 'Low Battery'

  - alias: Ring Doorbell Flash Lights
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.ring_front_door_ding
        to: 'on'
    action:
      ## See script here: https://github.com/isabellaalstrom/HomeAssistantConfiguration/blob/master/python_scripts/flash_lights_upstairs_hallway_and_yard.py
      - service: python_script.flash_lights_upstairs_hallway_and_yard