

sensor:
  - platform: command_line
    name: SSL cert expiry
    unit_of_measurement: days
    scan_interval: 10800
    command: !secret ssl_check_command

automation:
  - alias: 'SSL expiry notification'
    trigger:
      platform: numeric_state
      entity_id: sensor.ssl_cert_expiry
      below: 21
    action:
      service: notify.ios_isabellas_iphone_6s
      data:
        title: 'Warning'
        message: 'SSL certificate expires in 21 days and has not been automatically renewed'