homeassistant:
  customize:
    light.stairs_bottom_spot:
      icon: mdi:spotlight-beam
      friendly_name: Stairs Bottom Spot
        
    light.stairs_middle_spot:
      friendly_name: Stairs Middle Spot
      icon: mdi:spotlight-beam
        
    light.stairs_top_spot:
      friendly_name: Stairs Top Spot
      icon: mdi:spotlight-beam
        

    group.stairs_lights:
      friendly_name: Stairs Lights
        