homeassistant:
  customize:
    sensor.magic_mirror_rpi:
      icon: mdi:raspberrypi
    sensor.hass_rpi:
      icon: mdi:home-assistant      
    sensor.stefan_computer:
      icon: mdi:monitor
    sensor.isa_laptop:
      icon: mdi:laptop-windows
    sensor.isa_computer:
      icon: mdi:monitor
    sensor.asus_router:
      icon: mdi:wifi
    sensor.netgear_router:
      icon: mdi:wifi
    sensor.printer:
      icon: mdi:printer
    sensor.nas:
      icon: mdi:server
    sensor.chromecast_bedroom:
      icon: mdi:cast
    sensor.shield:
      icon: mdi:android
    # sensor.shield_2:
    #   icon: mdi:android
    sensor.ipad:
      icon: mdi:tablet-ipad
    sensor.movie_system:
      icon: mdi:speaker
    sensor.samsung65:
      icon: mdi:television
    sensor.hue_hub:
      icon: mdi:lightbulb-outline
    sensor.ikea_gateway:
      icon: mdi:google-keep
    sensor.xiaomi_gateway:
      icon: mdi:circle-outline
    sensor.ip_camera:
      icon: mdi:webcam
    sensor.galaxy_tab:
      icon: mdi:tablet-android
    sensor.samsung49:
      icon: mdi:television
    sensor.ir_blaster:
      icon: mdi:remote
    sensor.ir_blaster_bedroom:
      icon: mdi:remote
    sensor.ir_blaster_living_room:
      icon: mdi:remote
    sensor.withings_scale:
      icon: mdi:scale-bathroom
    sensor.sonos_3:
      icon: mdi:speaker
    sensor.milight_hub:
      icon: mdi:google-keep
    sensor.ring_doorbell:
      icon: mdi:doorbell-video
    sensor.ring_chime_pro:
      icon: mdi:wifi
    sensor.ring_chime:
      icon: mdi:bell-outline  
    
    
      
sensor:
  - platform: template
    sensors:
        milight_hub:
          friendly_name: 'Milight Hub'
          value_template: "{{ 'Online' if is_state('device_tracker.milight_controller', 'home') else 'Offline' }}"
        nas:
          friendly_name: 'Synology NAS'
          value_template: "{{ 'Online' if is_state('device_tracker.synology_nas', 'home') else 'Offline' }}"
        samsung65:
          friendly_name: 'Living Room TV'
          value_template: "{{ 'Online' if is_state('device_tracker.living_room_tv', 'home') else 'Offline' }}"
        samsung49:
          friendly_name: 'Bedroom TV'
          value_template: "{{ 'Online' if is_state('device_tracker.bedroom_tv', 'home') else 'Offline' }}"
        movie_system:
          friendly_name: 'Living Room Movie System'
          value_template: "{{ 'Online' if is_state('device_tracker.living_room_movie_system', 'home') else 'Offline' }}"
        netgear_router:
          friendly_name: 'Netgear Router'
          value_template: "{{ 'Online' if is_state('device_tracker.netgear_router', 'home') else 'Offline' }}"
        shield:
          friendly_name: 'NVidia Shield'
          value_template: "{{ 'Online' if is_state('device_tracker.nvidia_shield', 'home') else 'Offline' }}"
        # shield_2:
        #   friendly_name: 'NVidia Shield 2'
        #   value_template: "{{ 'Online' if is_state('device_tracker.shield', 'home') else 'Offline' }}"
        chromecast_bedroom:
          friendly_name: 'Chromecast Bedroom'
          value_template: "{{ 'Online' if is_state('device_tracker.chromecast_bedroom', 'home') else 'Offline' }}"
        stefan_computer:
          friendly_name: 'Stefan computer'
          value_template: "{{ 'Online' if is_state('device_tracker.stefan_computer', 'home') else 'Offline' }}"
        isa_computer:
          friendly_name: 'Isas computer'
          value_template: "{{ 'Online' if is_state('device_tracker.isa_computer', 'home') else 'Offline' }}"
        isa_laptop:
          friendly_name: 'Isas laptop'
          value_template: "{{ 'Online' if is_state('device_tracker.isa_laptop', 'home') else 'Offline' }}"
        printer:
          friendly_name: 'HP Printer'
          value_template: "{{ 'Online' if is_state('device_tracker.hp_printer', 'home') else 'Offline' }}"
        ipad:
          friendly_name: 'iPad'
          value_template: "{{ 'Online' if is_state('device_tracker.paddan', 'home') else 'Offline' }}"
        galaxy_tab:
          friendly_name: 'Galaxy Tab'
          value_template: "{{ 'Online' if is_state('device_tracker.android8c0fc07d9694a5a2', 'home') else 'Offline' }}"
        hue_hub:
          friendly_name: 'Philips Hue Gateway'
          value_template: "{{ 'Online' if is_state('device_tracker.philipshue', 'home') else 'Offline' }}"
        asus_router:
          friendly_name: 'Asus Router'
          value_template: "{{ 'Online' if is_state('device_tracker.router_asus', 'home') else 'Offline' }}"
        ip_camera:
          friendly_name: 'IP Camera'
          value_template: "{{ 'Online' if is_state('device_tracker.sannce_ip_camera', 'home') else 'Offline' }}"
        ir_blaster:
          friendly_name: 'Broadlink IR Blaster Hallway'
          value_template: "{{ 'Online' if is_state('device_tracker.broadlink_hallway', 'home') else 'Offline' }}"
        withings_scale:
          friendly_name: 'Withings scale'
          value_template: "{{ 'Online' if is_state('device_tracker.withings_scale', 'home') else 'Offline' }}"
        ir_blaster_bedroom:
          friendly_name: 'Broadlink IR Blaster Bedroom'
          value_template: "{{ 'Online' if is_state('device_tracker.broadlink_bedroom', 'home') else 'Offline' }}"
        # ir_blaster_living_room:
        #   friendly_name: 'Broadlink IR Blaster Living Room'
        #   value_template: "{{ 'Online' if is_state('device_tracker.broadlink_living_room', 'home') else 'Offline' }}"
        # ikea_gateway:
        #   friendly_name: 'Ikea Trådfri Gateway'
        #   value_template: "{{ 'Online' if is_state('device_tracker.tradfri_gateway', 'home') else 'Offline' }}"
        xiaomi_gateway:
          friendly_name: 'Xiaomi Gateway'
          value_template: "{{ 'Online' if is_state('device_tracker.xiaomi_gateway', 'home') else 'Offline' }}"
        sonos:
          friendly_name: 'Sonos'
          value_template: "{{ 'Online' if is_state('device_tracker.sonos_play_3', 'home') else 'Offline' }}"
        # magic_mirror_rpi:
        #   friendly_name: 'Magic Mirror Rpi'
        #   value_template: "{{ 'Online' if is_state('device_tracker.magic_mirror_rpi', 'home') else 'Offline' }}"
        # hass_rpi:
        #   friendly_name: 'Hass Rpi'
        #   value_template: "{{ 'Online' if is_state('device_tracker.hass_raspberry_pi', 'home') else 'Offline' }}"
        ring_doorbell:
          friendly_name: 'Ring'
          value_template: "{{ 'Online' if is_state('device_tracker.ring', 'home') else 'Offline' }}"
        ring_chime_pro:
          friendly_name: 'Ring Chime Pro'
          value_template: "{{ 'Online' if is_state('device_tracker.ring_chime_pro', 'home') else 'Offline' }}"
        ring_chime:
          friendly_name: 'Ring Chime Pro'
          value_template: "{{ 'Online' if is_state('device_tracker.ring_chime', 'home') else 'Offline' }}"

group:
  system_info_view:
    name: System info
    icon: mdi:lan
    view: yes
    entities:
      - device_tracker.isabella
      - device_tracker.stefan
      - group.device_states
      - group.computer_states
      - group.media_states
      - group.hass_card
      - group.internet_card
      - group.system_monitor_card
      - history_graph.internet_speed_tests
      - group.isabella
      - group.stefan
      - group.ring_front_door

  device_states:
    name: Device status
    entities:
    - sensor.printer
    - sensor.nas
    - sensor.ipad
    - sensor.galaxy_tab
    - sensor.ip_camera
    - sensor.ir_blaster
    - sensor.ir_blaster_bedroom
    - sensor.ir_blaster_living_room
    - sensor.withings_scale
    - sensor.hue_hub
    - sensor.milight_hub
    - sensor.ikea_gateway
    - sensor.xiaomi_gateway
    - sensor.hass_rpi
    - sensor.magic_mirror_rpi
    - sensor.ring_doorbell
    - sensor.ring_chime_pro
    - sensor.ring_chime

  computer_states:
    name: Computer status
    entities:
    - sensor.stefan_computer
    - sensor.isa_computer
    - sensor.isa_laptop

  media_states:
    name: Media player status
    entities:
    - sensor.samsung65
    - sensor.samsung49
    - sensor.movie_system
    - sensor.chromecast_bedroom
    - sensor.shield
    - sensor.shield_2
    - sensor.sonos

automation:
  - alias: 'Device Status'
    initial_state: 'on'
    trigger:
         - platform: state
           entity_id:
              - sensor.asus_router
              - sensor.netgear_router
              - sensor.printer
              - sensor.nas
              - sensor.hue_hub
              - sensor.ir_blaster
              - sensor.ir_blaster_bedroom
              - sensor.ip_camera
            #  - sensor.ir_blaster_living_room
              - sensor.xiaomi_gateway
              - sensor.milight_hub
              - sensor.ring_doorbell
              - sensor.ring_chime_pro
              - sensor.ring_chime
           to: 'offline'
           for:
             minutes: 5
    action:
      - service: notify.ios_isabellas_iphone_x
        data_template:
          title: 'Device {{ trigger.to_state.name }} is'
          message: >
            '{{ trigger.to_state.state }}'