homeassistant:
  customize:
    sensor.disk_used_:
      friendly_name: Rpi Disk Used
    sensor.process_mosquitto:
      friendly_name: 'Mosquitto'
      hidden: False
      icon: mdi:message-processing
    sensor.process_homebridge:
      friendly_name: 'Apple HomeKit'
      hidden: False
      icon: mdi:apple
    sensor.uptime:
      friendly_name: 'Hass Uptime'

group:
  system_monitor_card:
    name: System Monitor Hass Rpi
    entities:
      - alert.disk_use_critical
      - sensor.uptime
      - sensor.last_boot
      - sensor.disk_used__2
      - sensor.disk_used_
      - sensor.since_last_boot
      - sensor.process_homebridge
      - sensor.process_mosquitto

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_use
        arg: /
      - type: disk_free
        arg: /
      - type: memory_free
      - type: last_boot
      - type: since_last_boot
      - type: process
        arg: mosquitto
      - type: process
        arg: homebridge

  - platform: uptime
    unit_of_measurement: hours

binary_sensor:
  - platform: template
    sensors:
      critical_disk_use:
        value_template: '{{ states.sensor.disk_used_|float > 70 }}'
        friendly_name: 'Critical Disk Use'

alert:
  disk_use_critical:
    name: Rpi Disk Use Is Critical
    entity_id: binary_sensor.critical_disk_use
    repeat: 30
    skip_first: False
    notifiers:
      - ios_isabellas_iphone_6s

automation:
  - alias: 'Process Status'
    hide_entity: True
    trigger:
         - platform: state
           entity_id:
             - sensor.process_mosquitto
             - sensor.process_homebridge
           to: 'off'
           for:
             minutes: 1
    action:
      - service: notify.ios_isabellas_iphone_6s
        data_template:
          title: 'Process status'
          message: >
            '{{ trigger.to_state.attributes.friendly_name }} is {{ trigger.to_state.state }}'