input_boolean:
  hass_dev_mode:
    name: Hass developer mode
    initial: off
    icon: mdi:code-braces

sensor:
  - platform: mqtt
    state_topic: "homeassistant/sensor/uptime/state"
    name: Hass Rpi Uptime
    icon: mdi:clock-outline
  - platform: mqtt
    state_topic: "homeassistant/sensor/memory_free/state"
    name: Hass Rpi Free Memory
    icon: mdi:memory
  - platform: mqtt
    state_topic: "homeassistant/sensor/last_boot/state"
    name: Hass Rpi Last Boot
    icon: mdi:clock-outline
  - platform: mqtt
    state_topic: "homeassistant/sensor/disk_use_percent_/state"
    name: Hass Rpi Disk Use Percent
    icon: mdi:memory

binary_sensor:
  - platform: mqtt
    state_topic: "homeassistant/binary_sensor/critical_disk_use/state"
    name: Hass Rpi Critical Disk Use
    icon: mdi:floppy

automation:
  - alias: 'Hass Started'
    initial_state: 'on'
    trigger:
      platform: homeassistant
      # Event can also be 'shutdown'
      event: start
    action:
      - service: notify.pushbullet_isa
        data:
          title: 'Hass.io Online'
          message: 'Online'
      - service: python_script.summary
      - service: python_script.mailbox
        data_template:
          state: 'reset'


  - alias: 'Hass Ready'
    initial_state: 'on'
    trigger:
      platform: event
      event_type: zwave.network_ready
    action:
      - service: notify.pushbullet_isa
        data:
          title: 'Z-wave network now ready'
          message: 'Home Assistant'
      - service: python_script.device_tracker
        data_template:
          entity_id: 'input_select.stefan_status_dropdown'
          meta_entity: 'Stefan'
      - service: python_script.device_tracker
        data_template:
          entity_id: 'input_select.isa_status_dropdown'
          meta_entity: 'Isabella'
      # - delay:
      #     minutes: 1
      # - service: hassio.addon_start
      #   data:
      #     addon: a0d7b954_homebridge
      - delay: 00:05  # Waits 5 minutes
      - service: homekit.start

  - alias: 'Hass Stopped'
    initial_state: 'on'
    trigger:
      platform: homeassistant
      # Event can also be 'shutdown'
      event: shutdown
    action:
      - service: notify.pushbullet_isa
        data:
          title: 'Hass.io Offline'
          message: 'Offline'
      # - service: hassio.addon_stop
      #   data:
      #     addon: a0d7b954_homebridge

  - alias: Hass New Device Tracked
    trigger:
      platform: event
      event_type: device_tracker_new_device
    action:
      - service: notify.pushbullet_isa
        data_template:
          title: 'New device tracked'
          message: >
            {{trigger.event.data.host_name}} 
            ({{trigger.event.data.entity_id}})

  - alias: Hass Updater
    trigger:
      - platform: state
        entity_id: updater.updater
    action:
      - service: notify.pushbullet_isa
        data_template: 
          title: 'New Home Assistant Release Available'
          message: "Home Assistant  {{ states.updater.updater.state }}  is now available."
