homeassistant:
  customize:
    sensor.temperature_bedroom:
      friendly_name: Bedroom
    sensor.temperature_passage:
      friendly_name: Passage
    sensor.temperature_downstairs_bathroom:
      friendly_name: Downstairs Bathroom
    sensor.temperature_stefan:
      friendly_name: Stefans Room

    sensor.humidity_158d0001fd83e7:
      friendly_name: Stefans Room Humidity
      icon: mdi:water-percent
    sensor.humidity_158d0001235510:
      friendly_name: Bedroom Humidity
      icon: mdi:water-percent
    sensor.humidity_158d000123552c:
      friendly_name: Passage Humidity
      icon: mdi:water-percent
    sensor.humidity_158d0001a2a899:
      friendly_name: Downstairs Bathroom Humidity
      icon: mdi:water-percent

    sensor.illumination_34ce008bfc4b:
      friendly_name: Upstairs Hallway Lux
      icon: mdi:theme-light-dark
    sensor.illumination_158d000165ff1f:
      friendly_name: Living Room Lux 
      icon: mdi:theme-light-dark
    sensor.illumination_158d0001a66256:
      friendly_name: Hallway Lux
      icon: mdi:theme-light-dark


  customize_glob:
    sensor.*temperature*:
      templates:
        hs_color: "if (state < 23) return [0, 0];
        else if (state > 23) return [40, 70];
        else if (state > 25) return [0, 85];"
group:    
  temp_and_light:
    name: Temperature, light and humidity
    entities:
      # Passage
      # - sensor.temperature_passage
      # - sensor.humidity_158d000123552c
      # - sensor.passage_pir_luminance
      # Bedroom
      # - sensor.temperature_bedroom
      # - sensor.humidity_158d0001235510
      # Upstairs hallway      
      # - sensor.illumination_34ce008bfc4b
      # - sensor.upstairs_hallway_pir_luminance
      # Upstairs bathroom
      - sensor.fan_light    
      - sensor.fan_temperature  
      - sensor.fan_humidity
      # Downstairs bathroom
      # - sensor.temperature_downstairs_bathroom
      # - sensor.humidity_158d0001a2a899
      # # Isas room
      # - sensor.illumination_158d0001a66291
      # # Downstairs litterbox
      # - sensor.illumination_158d0001a24ef1
      # # pir 1+2
      # - sensor.illumination_158d000165ff1f
      # - sensor.illumination_158d0001a66256
      # Stefans room
      # - sensor.temperature_stefan
      # - sensor.humidity_158d0001fd83e7
      # - switch.stefan_radiator
      # Miflora
      - sensor.herbs_temperature
      - sensor.herbs_light_intensity
      - sensor.monstera_temperature
      - sensor.monstera_light_intensity
      - sensor.plant_temperature
      - sensor.plant_light_intensity