input_boolean:
  test:
    name: Test stuff
    initial: off

automation:
  - alias: 'Test Automation'
    initial_state: True
    trigger:
      - platform: state
        entity_id: input_boolean.test
        to: 'on'
    action:

      # - service: python_script.flash_light
      #   data_template:
      #     entity_id: light.bedside_lamp