homeassistant:
  customize:
    sensor.all_litter_box_visits_today:
      icon: mdi:poop
      friendly_name: All Litter Box Visits Today
    sensor.upstairs_litter_box_visits:
      icon: mdi:poop
      friendly_name: Upstairs Litter Box Visits
    binary_sensor.motion_sensor_158d0001a66291:
      friendly_name: Upstairs Litter Box
      hidden: true
    sensor.illumination_158d0001a66291:
      friendly_name: Isas Room Lux
    sensor.upstairs_litter_box:
      extra_badge:
        entity_id: sensor.upstairs_litter_box_visits

#-------------------------------------------

sensor:
  - platform: mqtt
    state_topic: "litterbox/upstairs/count"
    name: Upstairs Litter Box Visits
    unit_of_measurement: "visits"
  - platform: mqtt
    state_topic: "litterbox/all/count"
    name: All Litter Box Visits Today
    unit_of_measurement: "visits"
  - platform: template
    sensors:
      upstairs_litter_box:
        friendly_name: 'Upstairs Litterbox'
        value_template: '{% if is_state("binary_sensor.motion_sensor_158d0001a66291", "on") %}In use{% else %}Clear{% endif %}'
        icon_template: '{% if is_state("binary_sensor.motion_sensor_158d0001a66291", "on") %}mdi:cat{% else %}mdi:paw-off{% endif %}'

input_select:
  ulitterbox_state:
    name: Upstairs Litterbox State
    options:
      - Clean
      - Dirty
      - Cleaning
    initial: Clean
    icon: mdi:paw
#-------------------------------------------

script:
  ifttt_litterbox_day_summary:
    sequence:
      - service: ifttt.trigger
        data_template: {"event":"Litterbox_Day_Summary", "value1":"", "value2":""}

#-------------------------------------------

automation:
  - alias: Litterbox Sensors Set To Zero On Start
    initial_state: 'on'
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: python_script.ulitter_reset
      - service: python_script.dlitter_reset
      - service: python_script.all_litter_reset
      
  - alias: Litterbox Upstairs Counter
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_158d0001a66291
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: >
            {% if states.automation.litterbox_upstairs_counter.last_triggered is not none %}
              {% if as_timestamp(now()) | int   -  as_timestamp(states.automation.litterbox_upstairs_counter.attributes.last_triggered) | int > 300 %} true {% else %} false
              {% endif %}
            {% else %}
            false
            {% endif %}
        - condition: or
          conditions:
            - condition: state
              entity_id: input_select.ulitterbox_state
              state: 'Clean'
            - condition: state
              entity_id: input_select.ulitterbox_state
              state: 'Dirty'
    action:
      - service: python_script.ulitter_counter
      - service: python_script.all_litter_counter
      - service: input_select.select_option
        data:
          entity_id: input_select.ulitterbox_state
          option: 'Dirty'
      - service: ifttt.trigger
        data: {"event":"Litterbox_Visit", "value1":"Upstairs"}

  - alias: Litterbox Upstairs Cleaning Notification
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.upstairs_litter_box_visits
        above: '1'
      - platform: state
        entity_id: device_tracker.isabellas_iphone_6s
        to: 'home'
        for:
          minutes: 10
    condition:
      condition: and
      conditions:
        - condition: time
          after: '07:00:00'
          before: '23:00:00'
        - condition: state
          entity_id: device_tracker.isabellas_iphone_6s
          state: 'home'
        - condition: numeric_state
          entity_id: sensor.upstairs_litter_box_visits
          above: '1'
    action:
      - service: notify.ios_isabellas_iphone_6s
        data_template:
          title: 'Time to clean'
          message: >
            '{{ states('sensor.upstairs_litter_box_visits') }} visits to upstairs litterbox'

  - alias: Litterbox Upstairs Cleaning Mode
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.white3
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_select.ulitterbox_state
          state: 'Dirty'
        - condition: state
          entity_id: input_select.ulitterbox_state
          state: 'Clean'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.ulitterbox_state
          option: 'Cleaning'

  - alias: Litterbox Upstairs Cleaned
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.white3
    condition:
      condition: state
      entity_id: input_select.ulitterbox_state
      state: 'Cleaning'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.ulitterbox_state
          option: 'Clean'
      - service: python_script.ulitter_reset

  - alias: Litterbox All Counter Reset At Midnight
    initial_state: 'on'
    trigger:
      - platform: time
        at: '23:59:00'
    action:
      - service: script.ifttt_litterbox_day_summary
        data_template:
          value1: "{{ states('sensor.all_litter_box_visits_today') }}"
      - service: python_script.all_litter_reset

# #-----------------------------------------

# switch:
#   - platform: mqtt
#     name: "UpstairsLitterBox"
#     state_topic: "UpstairsLitterBox/Button/state"
#     command_topic: "UpstairsLitterBox/gpio/13"
#     payload_on: "1"
#     payload_off: "0"
#     optimistic: false
#     qos: 0

#   - platform: mqtt
#     name: "UpstairsLitterBoxBlueLed"
#     state_topic: "UpstairsLitterBox/blueled/state"
#     command_topic: "UpstairsLitterBox/gpio/15"
#     payload_on: "1"
#     payload_off: "0"
#     optimistic: false
#     qos: 0

#   - platform: mqtt
#     name: "UpstairsLitterBoxGreenLed"
#     state_topic: "UpstairsLitterBox/greenled/state"
#     command_topic: "UpstairsLitterBox/gpio/12"
#     payload_on: "1"
#     payload_off: "0"
#     optimistic: false
#     qos: 0

#   - platform: mqtt
#     name: "UpstairsLitterBoxRedLed"
#     state_topic: "UpstairsLitterBox/redled/state"
#     command_topic: "UpstairsLitterBox/gpio/02"
#     payload_on: "1"
#     payload_off: "0"
#     optimistic: false
#     qos: 0

# #-------------------------------------------

# binary_sensor:
#   - platform: mqtt
#     name: "Upstairs Litter Box Pir"
#     state_topic: "UpstairsLitterBox/pir/state"
#     command_topic: "UpstairsLitterBox/gpio/14"
#     payload_on: "1"
#     payload_off: "0"
#     optimistic: false
#     qos: 0

#-------------------------------------------