homeassistant:
  customize:
    binary_sensor.door_bathroom_cabinet:
      friendly_name: Bathroom Cabinet Door

alert: 
  bathroom_cabinet_door_open:
    name: Bathroom Cabinet Door left open
    done_message: Bathroom Cabinet Door closed
    entity_id: binary_sensor.door_bathroom_cabinet
    state: 'on'
    repeat:
      - 2
      - 15
      - 30
      - 60
    skip_first: True
    notifiers:
      - ios_isabellas_iphone_x

