homeassistant:
  customize:   
    light.walk_in_closet_lights:
      homebridge_visible: true
      homebridge_name: Walk in closet lights
    light.walk_in_closet_1:
      homebridge_visible: false
    light.walk_in_closet_2:
      homebridge_visible: false
    light.walk_in_closet_3:
      homebridge_visible: false
    light.walk_in_closet_4:
      homebridge_visible: false
      
light:
  - platform: group
    name: Walk in closet lights
    entities:
      - light.walk_in_closet_1
      - light.walk_in_closet_2
      - light.walk_in_closet_3
      - light.walk_in_closet_4

group:
  walk_in_closet_lights:
    name: Walk In Closet Spotlights
    icon: mdi:spotlight-beam
    entities:
      - light.walk_in_closet_1
      - light.walk_in_closet_2
      - light.walk_in_closet_3
      - light.walk_in_closet_4