homeassistant:
  customize:
    binary_sensor.switch_158d00019d674a:
      friendly_name: Walk In Closet Dimmer

group:
  walk_in_closet_lights:
    name: Walk In Closet Spotlights
    icon: mdi:spotlight-beam
    entities:
      - light.walk_in_closet_1
      - light.walk_in_closet_2
      - light.walk_in_closet_3
      - light.walk_in_closet_4