homeassistant:
  customize:
    binary_sensor.switch_158d0001243520:
      friendly_name: Bed Switch
      homebridge_hidden: true
   
    binary_sensor.door_window_sensor_158d0001a3e3a4:
      friendly_name: Bathroom Cabinet Door

    light.gateway_light_34ce008bfc4b:
      friendly_name: Xiaomi Gateway Nightlight
    sensor.illumination_34ce008bfc4b:
      friendly_name: Xiaomi Gateway Lumen

alert: 
  bathroom_cabinet_door_open:
    name: Bathroom Cabinet Door left open
    done_message: Bathroom Cabinet Door closed
    entity_id: binary_sensor.door_window_sensor_158d0001a3e3a4
    state: 'on'
    repeat: 2
    skip_first: True
    notifiers:
      - ios_isabellas_iphone_6s

automation:
  - alias: Light Bedside Bed Switch
    initial_state: 'on'
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001243520
        click_type: single
    action:
      service: light.toggle
      entity_id: light.bedside_lamp

  - alias: Light Bedroom Bed Switch
    initial_state: 'on'
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001243520
        click_type: double
    action:
      service: light.toggle
      entity_id: light.bedroom_ceiling_light
  - alias: Light All Bed Switch
    initial_state: 'on'
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001243520
        click_type: long_click_press
    action:
      service: homeassistant.turn_off
      entity_id: group.inside_lights_card