homeassistant:
  customize:



    binary_sensor.door_window_sensor_158d0001a3e3a4:
      friendly_name: Bathroom Cabinet Door

    light.gateway_light_34ce008bfc4b:
      friendly_name: Upstairs Hallway Nightlight
      homebridge_visible: false
      emulated_hue_hidden: false
      emulated_hue_name: "Nightlight"

    sensor.illumination_34ce008bfc4b:
      friendly_name: Upstairs Hallway Illumination
      icon: mdi:theme-light-dark

alert: 
  bathroom_cabinet_door_open:
    name: Bathroom Cabinet Door left open
    done_message: Bathroom Cabinet Door closed
    entity_id: binary_sensor.door_window_sensor_158d0001a3e3a4
    state: 'on'
    repeat: 2
    skip_first: True
    notifiers:
      - ios_isabellas_iphone_6s
