homeassistant:
  customize:

    binary_sensor.switch_158d0001a5e3c4:
      friendly_name: Switch 1
    binary_sensor.switch_158d00016c0a49:
      friendly_name: Switch 2
    binary_sensor.switch_158d00019d674a:
      friendly_name: Switch 3
    binary_sensor.door_window_sensor_158d0001a3e3a4:
      friendly_name: Bathroom Cabinet Door

    light.gateway_light_34ce008bfc4b:
      friendly_name: Nightlight
      homebridge_visible: false
    sensor.illumination_34ce008bfc4b:
      friendly_name: Upstairs Hallway Nightlight
      icon: mdi:theme-light-dark




alert: 
  bathroom_cabinet_door_open:
    name: Bathroom Cabinet Door left open
    done_message: Bathroom Cabinet Door closed
    entity_id: binary_sensor.door_window_sensor_158d0001a3e3a4
    state: 'on'
    repeat: 2
    skip_first: True
    notifiers:
      - ios_isabellas_iphone_6s
